Repository valkey-io/valkey-glide, pull requests merged in 2025-07, with the labels that each got.

#4236 C#: Add response checks for batch for every command
  csharp/sources/Valkey.Glide/BaseClient.Commands.cs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/Internals/Cmd.cs
  csharp/sources/Valkey.Glide/Internals/Helpers.cs
  csharp/sources/Valkey.Glide/Internals/ResponseConverters.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatch.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedBatchTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
Labels: C#

#4207 C#: Add RESP2 client to IT.
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C# 🥅, testing

#4292 C# compatibility: `IDatabase`
  .github/workflows/csharp.yml
  benchmarks/csharp/Program.cs
  csharp/.editorconfig
  csharp/sources/Valkey.Glide/Abstract/ConnectionMultiplexer.cs
  csharp/sources/Valkey.Glide/Abstract/Database.cs
  csharp/sources/Valkey.Glide/Abstract/IConnectionMultiplexer.cs
  csharp/sources/Valkey.Glide/Commands/IDatabase.cs
  csharp/sources/Valkey.Glide/Commands/IStringBaseCommands.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/PhysicalConnection.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ValkeyValue.cs
  csharp/tests/Valkey.Glide.IntegrationTests/DBTests.cs
Labels: C# 🥅, Compatibility 🧭

#4300 CI: Fix GHA
  .github/workflows/full-matrix-tests.yml
Labels: CI/CD ⚒️

#4291 C#: Set Commands
  csharp/sources/Valkey.Glide/BaseClient.SetCommands.cs
  csharp/sources/Valkey.Glide/Commands/Constants/Constants.cs
  csharp/sources/Valkey.Glide/Commands/ISetCommands.cs
  csharp/sources/Valkey.Glide/GlideString.cs
  csharp/sources/Valkey.Glide/Internals/FFI.cs
  csharp/sources/Valkey.Glide/Internals/Request.SetCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.SetCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchSetCommands.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ValkeyValue.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SetCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/GildeStringTests.cs
Labels: C# 🥅

#4320 CI: Add actions:write permission to full-matrix-tests-sweeper
  .github/workflows/full-matrix-tests-sweeper.yml
Labels: CI/CD ⚒️

#4206 C#: Add option to use running server(s) for IT.
  csharp/DEVELOPER.md
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C# 🥅, testing 🧪

#4308 C#: Add Set Commands Command Flag Exception
  csharp/sources/Valkey.Glide/BaseClient.SetCommands.cs
  csharp/sources/Valkey.Glide/Commands/ISetCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.SetCommands.cs
Labels: C# 🥅

#4301 C#: Add String commands
  benchmarks/csharp/Program.cs
  csharp/sources/Valkey.Glide/BaseClient.Commands.cs
  csharp/sources/Valkey.Glide/BaseClient.StringCommands.cs
  csharp/sources/Valkey.Glide/Commands/IStringBaseCommands.cs
  csharp/sources/Valkey.Glide/Internals/FFI.cs
  csharp/sources/Valkey.Glide/Internals/Helpers.cs
  csharp/sources/Valkey.Glide/Internals/Request.String.cs
  csharp/sources/Valkey.Glide/Internals/Request.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.StringCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchStringCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/DBTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedBatchTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StringCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
Labels: C# 🥅

#4371 C#: batch compatibility
  csharp/sources/Valkey.Glide/Abstract/ConnectionMultiplexer.cs
  csharp/sources/Valkey.Glide/Abstract/Database.cs
  csharp/sources/Valkey.Glide/Abstract/IBatch.cs
  csharp/sources/Valkey.Glide/Abstract/IConnectionMultiplexer.cs
  csharp/sources/Valkey.Glide/Abstract/IDatabase.cs
  csharp/sources/Valkey.Glide/Abstract/IDatabaseAsync.cs
  csharp/sources/Valkey.Glide/Abstract/ITransaction.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyBatch.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyTransaction.cs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/Commands/IDatabase.cs
  csharp/sources/Valkey.Glide/Commands/IGenericClusterCommands.cs
  csharp/sources/Valkey.Glide/Commands/IGenericCommands.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/DBTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedBatchTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
Labels: C# 🥅

#4372 C#: Add ZRem command
  csharp/sources/Valkey.Glide/BaseClient.SortedSetCommands.cs
  csharp/sources/Valkey.Glide/Commands/ISortedSetCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.SortedSetCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.SortedSetCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchSortedSetCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SortedSetCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/SortedSetCommandTests.cs
Labels: C# 🥅

#4409 C#: String commands GA
  csharp/sources/Valkey.Glide/BaseClient.StringCommands.cs
  csharp/sources/Valkey.Glide/Commands/IStringBaseCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.String.cs
  csharp/sources/Valkey.Glide/Internals/ResponseHandler.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.StringCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchStringCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StringCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
Labels: C# 🥅

#4351 C#: Add HashCommand support
  csharp/sources/Valkey.Glide/Abstract/IDatabaseAsync.cs
  csharp/sources/Valkey.Glide/BaseClient.HashCommands.cs
  csharp/sources/Valkey.Glide/Commands/IConnectionManagementCommands.cs
  csharp/sources/Valkey.Glide/Commands/IHashCommands.cs
  csharp/sources/Valkey.Glide/Commands/IListBaseCommands.cs
  csharp/sources/Valkey.Glide/Commands/ISetCommands.cs
  csharp/sources/Valkey.Glide/Commands/ISortedSetCommands.cs
  csharp/sources/Valkey.Glide/Internals/GuardClauses.cs
  csharp/sources/Valkey.Glide/Internals/Request.HashCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.SetCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.cs
  csharp/sources/Valkey.Glide/Internals/ResponseConverters.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.HashCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchHashCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ConsoleCapturingTestBase.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ConsoleOutputInterceptor.cs
  csharp/tests/Valkey.Glide.IntegrationTests/HashCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SetCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
Labels: C# 🥅

#4413 C#: fix endpoint string conversion
  csharp/sources/Valkey.Glide/Abstract/ConnectionMultiplexer.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyServer.cs
  csharp/sources/Valkey.Glide/Internals/Utils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ServerTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C# 🥅

#4412 C# compatibility: `execute` aka custom command
  csharp/sources/Valkey.Glide/Abstract/ConfigurationOptions.cs
  csharp/sources/Valkey.Glide/Abstract/ConnectionMultiplexer.cs
  csharp/sources/Valkey.Glide/Abstract/Database.cs
  csharp/sources/Valkey.Glide/Abstract/IDatabase.cs
  csharp/sources/Valkey.Glide/Abstract/IDatabaseAsync.cs
  csharp/sources/Valkey.Glide/Abstract/IServer.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyBatch.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyServer.cs
  csharp/sources/Valkey.Glide/BaseClient.ConnectionManagementCommands.cs
  csharp/sources/Valkey.Glide/BaseClient.ListCommands.cs
  csharp/sources/Valkey.Glide/BaseClient.StringCommands.cs
  csharp/sources/Valkey.Glide/Commands/IConnectionManagementCommands.cs
  csharp/sources/Valkey.Glide/Commands/IGenericBaseCommands.cs
  csharp/sources/Valkey.Glide/Commands/IHashCommands.cs
  csharp/sources/Valkey.Glide/Commands/IListCommands.cs
  csharp/sources/Valkey.Glide/Commands/IServerManagementClusterCommands.cs
  csharp/sources/Valkey.Glide/Commands/IServerManagementCommands.cs
  csharp/sources/Valkey.Glide/Commands/ISetCommands.cs
  csharp/sources/Valkey.Glide/Commands/ISortedSetCommands.cs
  csharp/sources/Valkey.Glide/Commands/IStringCommands.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/Internals/Request.ServerManagement.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchListCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchStringCommands.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ClientKillFilter.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/GeoEntry.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ListPopResult.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ResultTypeExtensions.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/SortedSetEntry.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/SortedSetPopResult.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/StreamAutoClaimIdsOnlyResult.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/StreamAutoClaimResult.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ValkeyKey.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ValkeyResult.cs
  csharp/sources/Valkey.Glide/abstract_APITypes/ValkeyValue.cs
  csharp/sources/Valkey.Glide/abstract_Enums/ClientFlags.cs
  csharp/sources/Valkey.Glide/abstract_Enums/ConnectionFailureType.cs
  csharp/sources/Valkey.Glide/abstract_Enums/Proxy.cs
  csharp/sources/Valkey.Glide/abstract_Enums/SaveType.cs
  csharp/sources/Valkey.Glide/abstract_Enums/ServerType.cs
  csharp/sources/Valkey.Glide/abstract_Enums/ValkeyType.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ServerTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SortedSetCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StringCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C# 🥅

#4411 C#: compatible transaction conditions
  csharp/sources/Valkey.Glide/Abstract/Condition.cs
  csharp/sources/Valkey.Glide/Abstract/ITransaction.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyBatch.cs
  csharp/sources/Valkey.Glide/Abstract/ValkeyTransaction.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTests.cs
Labels: C# 🥅

#4467 C#: Sorted Set Public Preview Commands
  .gitignore
  csharp/sources/Valkey.Glide/BaseClient.SortedSetCommands.cs
  csharp/sources/Valkey.Glide/Commands/Constants/Constants.cs
  csharp/sources/Valkey.Glide/Commands/ISortedSetCommands.cs
  csharp/sources/Valkey.Glide/Commands/Options/ZCountOptions.cs
  csharp/sources/Valkey.Glide/Commands/Options/ZRangeOptions.cs
  csharp/sources/Valkey.Glide/Internals/Request.SortedSetCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.SortedSetCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchSortedSetCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SortedSetCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/BoundaryTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/SortedSetCommandTests.cs
Labels: C# 🥅

#4402 C#: List Commands batch 1
  csharp/sources/Valkey.Glide/BaseClient.ListCommands.cs
  csharp/sources/Valkey.Glide/Commands/IListCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.List.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.ListCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchListCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ListCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
Labels: C# 🥅

#4374 GO: Lazy connect implementation
  CHANGELOG.md
  go/config/config.go
  go/config/config_test.go
  go/integTest/connection_test.go
  go/integTest/glide_test_suite_test.go
Labels: go 🏃

#4458 Java: Jedis compatibility layer simple commands added for Jedis.java
  java/client/src/main/java/compatibility/clients/jedis/DefaultJedisClientConfig.java
  java/client/src/main/java/compatibility/clients/jedis/Jedis.java
  java/client/src/main/java/compatibility/clients/jedis/JedisCluster.java
  java/client/src/main/java/compatibility/clients/jedis/JedisPool.java
  java/client/src/main/java/compatibility/clients/jedis/SSLParametersUtils.java
  java/client/src/main/java/compatibility/clients/jedis/args/BitCountOption.java
  java/client/src/main/java/compatibility/clients/jedis/args/ExpiryOption.java
  java/client/src/main/java/compatibility/clients/jedis/params/BitPosParams.java
  java/client/src/main/java/compatibility/clients/jedis/params/GetExParams.java
  java/client/src/main/java/compatibility/clients/jedis/params/ScanParams.java
  java/client/src/main/java/compatibility/clients/jedis/params/SetParams.java
  java/client/src/main/java/compatibility/clients/jedis/resps/ScanResult.java
  java/client/src/main/java/module-info.java
  java/client/src/test/java/compatibility/clients/jedis/JedisMethodsTest.java
  java/integTest/build.gradle
  java/integTest/src/test/java/compatibility/jedis/JedisPoolTest.java
  java/integTest/src/test/java/compatibility/jedis/JedisTest.java
Labels: java ☕, Compatibility 🧭

#4495 C#: String Commands (GA)
  csharp/sources/Valkey.Glide/BaseClient.StringCommands.cs
  csharp/sources/Valkey.Glide/Commands/Constants/Constants.cs
  csharp/sources/Valkey.Glide/Commands/IStringCommands.cs
  csharp/sources/Valkey.Glide/Internals/Request.String.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.StringCommands.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatchStringCommands.cs
  csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StringCommandTests.cs
  csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
Labels: C# 🥅

#4478 Update C# benchmark Program.cs to fix benchmark timing collection.
  benchmarks/csharp/Program.cs
Labels: C# 🥅, testing 🧪
