Repository valkey-io/valkey-glide, pull requests merged in 2025-02, with the labels that each got.

#3021 Go: Add command zinter
  go/api/base_client.go
  go/api/options/constants.go
  go/api/options/weight_aggregate_options.go
  go/api/options/zinter_options.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2978 SET IFEQ command implemented in Java + tests
  CHANGELOG.md
  java/client/src/main/java/glide/api/commands/StringBaseCommands.java
  java/client/src/main/java/glide/api/models/commands/SetOptions.java
  java/client/src/test/java/glide/api/GlideClientTest.java
Labels: java

#3032 Go: ZDiff command added
  go/api/base_client.go
  go/api/options/constants.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#3034 Go: Add ZDiffStore command
  go/api/base_client.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2986 Core: Add AzAffinityReplicasAndPrimary Read Strategy
  CHANGELOG.md
  glide-core/redis-rs/redis/src/aio/mod.rs
  glide-core/redis-rs/redis/src/client.rs
  glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
  glide-core/redis-rs/redis/src/cluster_async/connections_logic.rs
  glide-core/redis-rs/redis/src/cluster_async/mod.rs
  glide-core/redis-rs/redis/src/cluster_client.rs
  glide-core/redis-rs/redis/src/cluster_slotmap.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
  glide-core/src/client/mod.rs
  glide-core/src/client/standalone_client.rs
  glide-core/src/client/types.rs
  glide-core/src/protobuf/connection_request.proto
  glide-core/tests/test_standalone_client.rs
  node/src/BaseClient.ts
Labels: Feature, Rust core

#2994 Go: `XINFO STREAM`.
  go/api/base_client.go
  go/api/options/constants.go
  go/api/options/stream_options.go
  go/api/response_handlers.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#3053 Go: add ZInterStore
  go/api/base_client.go
  go/api/options/zinter_options.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#3071 Python: add AZAffinityReplicasAndPrimary ReadFrom strategy support
  CHANGELOG.md
  python/python/glide/config.py
  python/python/tests/test_config.py
  python/python/tests/test_read_from_strategy.py
Labels: python, testing

#3083 Java: Add AzAffinityReplicasAndPrimary Read Strategy
  CHANGELOG.md
  java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/ReadFrom.java
  java/client/src/main/java/glide/managers/ConnectionManager.java
  java/client/src/test/java/glide/managers/ConnectionManagerTest.java
  java/integTest/src/test/java/glide/ConnectionTests.java
Labels: java, testing

#3035 updating xUnit, adding xUnit analyser rules and guidelines
  CHANGELOG.md
  csharp/.editorconfig
  csharp/DEVELOPER.md
  csharp/tests/Integration/IntegrationTestBase.cs
  csharp/tests/tests.csproj
Labels: C#

#3087 Fix flaky test set for more margine for ttl
  node/tests/SharedTests.ts
Labels: node, testing

#3062 Go: CD pipeline
  .github/json_matrices/build-matrix.json
  .github/workflows/go-cd.yml
  go/.gitignore
  go/Cargo.toml
  go/Makefile
  go/api/base_client.go
  go/api/bitmap_commands.go
  go/api/command_options.go
  go/api/config.go
  go/api/config/request_routing_config.go
  go/api/config_test.go
  go/api/connection_management_cluster_commands.go
  go/api/connection_management_commands.go
  go/api/errors/errors.go
  go/api/generic_base_commands.go
  go/api/generic_cluster_commands.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/hash_commands.go
  go/api/options/bitcount_options.go
  go/api/options/bitfield_options.go
  go/api/options/db_size_options.go
  go/api/options/ping_options.go
  go/api/options/route_options.go
  go/api/options/sort_options.go
  go/api/options/stream_options.go
  go/api/options/weight_aggregate_options.go
  go/api/options/zadd_options.go
  go/api/options/zmpop_options.go
  go/api/options/zrange_options.go
  go/api/response_handlers.go
  go/api/server_management_cluster_commands.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/api/stream_commands.go
  go/benchmarks/glide_benchmark_client.go
  go/benchmarks/go.mod
  go/examples/main.go
  go/go.mod
  go/integTest/cluster_commands_test.go
  go/integTest/connection_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/json_module_test.go
  go/integTest/request_routing_config_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/vss_module_test.go
Labels: go, CI/CD

#2835 Add node test for checking exported symbols
  .github/workflows/build-node-wrapper/action.yml
  .github/workflows/node-create-package-file/action.yml
  node/DEVELOPER.md
  node/README.md
  node/npm/glide/index.ts
  node/npm/glide/jest.config.js
  node/npm/glide/package.json
  node/npm/glide/tests/ExportedSymbols.test.ts
  node/npm/glide/tests/tsconfig.json
  node/rust-client/src/lib.rs
  node/src/BaseClient.ts
  node/src/Commands.ts
  node/src/Transaction.ts
  node/src/server-modules/GlideFtOptions.ts
Labels: node

#3103 Go: CD pipeline (for release-1.3)
  .github/json_matrices/build-matrix.json
  .github/workflows/go-cd.yml
  go/.gitignore
  go/Cargo.toml
  go/Makefile
  go/api/base_client.go
  go/api/bitmap_commands.go
  go/api/command_options.go
  go/api/config.go
  go/api/config/request_routing_config.go
  go/api/config_test.go
  go/api/connection_management_cluster_commands.go
  go/api/connection_management_commands.go
  go/api/errors/errors.go
  go/api/generic_base_commands.go
  go/api/generic_cluster_commands.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/hash_commands.go
  go/api/options/bitcount_options.go
  go/api/options/bitfield_options.go
  go/api/options/db_size_options.go
  go/api/options/ping_options.go
  go/api/options/route_options.go
  go/api/options/sort_options.go
  go/api/options/stream_options.go
  go/api/options/weight_aggregate_options.go
  go/api/options/zadd_options.go
  go/api/options/zmpop_options.go
  go/api/options/zrange_options.go
  go/api/response_handlers.go
  go/api/server_management_cluster_commands.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/api/stream_commands.go
  go/benchmarks/glide_benchmark_client.go
  go/benchmarks/go.mod
  go/examples/main.go
  go/go.mod
  go/integTest/cluster_commands_test.go
  go/integTest/connection_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/json_module_test.go
  go/integTest/request_routing_config_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/vss_module_test.go
Labels: go, CI/CD

#3098 Go: Add IFEQ to SetOptions
  go/api/base_client.go
  go/api/command_options.go
  go/integTest/shared_commands_test.go
Labels: go

#3112 Update task.yml
  .github/ISSUE_TEMPLATE/task.yml
Labels: CI/CD, tools

#3123 Rust: Fix opentelemetry_sdk dependency
  CHANGELOG.md
  glide-core/telemetry/Cargo.toml
Labels: dependency

#3014 Fix dependency on redis-cli and redis-server to pass tests
  csharp/DEVELOPER.md
  eslint.config.mjs
  glide-core/redis-rs/redis/Cargo.toml
  glide-core/redis-rs/redis/tests/support/cluster.rs
  glide-core/redis-rs/redis/tests/support/mod.rs
  go/DEVELOPER.md
  node/.ort.yml
  node/DEVELOPER.md
  node/hybrid-node-tests/commonjs-test/commonjs-test.cjs
  node/hybrid-node-tests/commonjs-test/package.json
  node/hybrid-node-tests/ecmascript-test/ecmascript-test.mjs
  node/hybrid-node-tests/ecmascript-test/package.json
  node/npm/glide/package.json
  node/npm/glide/tests/ExportedSymbols.test.ts
  node/package.json
  node/tests/AsyncClient.test.ts
  node/tests/GlideClusterClient.test.ts
  node/tests/TestUtilities.ts
  python/DEVELOPER.md
  utils/TestUtils.ts
  utils/cluster_manager.py
Labels: bug, node, testing

#3055 Move all documentation examples to separate test files
  go/Makefile
  go/api/base_client.go
  go/api/bitmap_commands_test.go
  go/api/config.go
  go/api/config_test.go
  go/api/connection_management_commands_test.go
  go/api/example_utils.go
  go/api/generic_base_commands_test.go
  go/api/generic_commands_test.go
  go/api/glide_client.go
  go/api/hash_commands_test.go
  go/api/hyperloglog_commands_test.go
  go/api/list_commands_test.go
  go/api/server_management_commands_test.go
  go/api/set_commands_test.go
  go/api/sorted_set_commands_test.go
  go/api/stream_commands_test.go
  go/api/string_commands_test.go
  go/benchmarks/main.go
  go/examples/main.go
  go/integTest/request_routing_config_test.go
Labels: go, docs

#3122 Avoid using ephemeral runners in publishing workflows since ephemeral runners are new feature and using them during the release can complicate the process.
  .github/workflows/go-cd.yml
  .github/workflows/java-cd.yml
  .github/workflows/npm-cd.yml
  .github/workflows/pypi-cd.yml
Labels: CI/CD

#3130 [Backport `1.3`] Rust: Fix opentelemetry_sdk dependency (#3123)
  CHANGELOG.md
  glide-core/telemetry/Cargo.toml
Labels: Rust core, dependency

#3132 [Backport 1.3] Move all documentation examples to separate test files (#3055)
  go/Makefile
  go/api/base_client.go
  go/api/bitmap_commands_test.go
  go/api/config.go
  go/api/config_test.go
  go/api/connection_management_commands_test.go
  go/api/example_utils.go
  go/api/generic_base_commands_test.go
  go/api/generic_commands_test.go
  go/api/glide_client.go
  go/api/hash_commands_test.go
  go/api/hyperloglog_commands_test.go
  go/api/list_commands_test.go
  go/api/options/zinter_options.go
  go/api/server_management_commands_test.go
  go/api/set_commands_test.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/api/stream_commands_test.go
  go/api/string_commands_test.go
  go/benchmarks/main.go
  go/examples/main.go
  go/integTest/request_routing_config_test.go
  go/integTest/shared_commands_test.go
Labels: Feature, go

#3104 Go: Fix command options classes.
  go/api/base_client.go
  go/api/bitmap_commands_test.go
  go/api/generic_base_commands.go
  go/api/generic_base_commands_test.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/hash_commands_test.go
  go/api/list_commands.go
  go/api/list_commands_test.go
  go/api/options/base_scan_options.go
  go/api/options/bitcount_options.go
  go/api/options/command_options.go
  go/api/options/constants.go
  go/api/options/db_size_options.go
  go/api/options/echo_options.go
  go/api/options/hscan_options.go
  go/api/options/ping_options.go
  go/api/options/sort_options.go
  go/api/options/stream_options.go
  go/api/options/weight_aggregate_options.go
  go/api/options/zadd_options.go
  go/api/options/zcount_options.go
  go/api/options/zinter_options.go
  go/api/options/zrange_options.go
  go/api/options/zscan_options.go
  go/api/response_handlers.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_commands.go
  go/api/set_commands_test.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/api/string_commands.go
  go/api/string_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/json_module_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/vss_module_test.go
Labels: go

#3133 [Backport `1.3`] Backport #3122 into release 1.3 branch
  .github/workflows/go-cd.yml
  .github/workflows/java-cd.yml
  .github/workflows/npm-cd.yml
  .github/workflows/pypi-cd.yml
Labels: CI/CD

#3108 Node: rename modules batching
  node/npm/glide/index.ts
  node/src/server-modules/GlideJson.ts
  node/tests/ServerModules.test.ts
  node/tests/TestUtilities.ts
Labels: node

#3135 Go: Updated developer guide for docs, examples, naming conventions
  go/DEVELOPER.md
Labels: go, docs

#3153 Go: Updated developer guide for docs, examples, naming conventions
  go/DEVELOPER.md
Labels: go

#3152 GO: fix broken examples that fail
  go/api/bitmap_commands_test.go
  go/api/generic_base_commands_test.go
  go/api/hash_commands_test.go
  go/api/set_commands_test.go
Labels: go

#3151 GO: Fix func name casing
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/generic_base_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3148 GO: Move remaining comment examples to test files
  go/api/base_client.go
  go/api/bitmap_commands_test.go
  go/api/server_management_commands_test.go
  go/api/sorted_set_commands_test.go
  go/api/stream_commands_test.go
Labels: go

#3155 Node: Fix NPM CD tag
  .github/workflows/npm-cd.yml
  CHANGELOG.md
Labels: node, CI/CD

#3158 Go: Examples update cherrypick
  go/api/base_client.go
  go/api/bitmap_commands_test.go
  go/api/generic_base_commands.go
  go/api/generic_base_commands_test.go
  go/api/hash_commands_test.go
  go/api/server_management_commands_test.go
  go/api/set_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3154 Go: Add `GlideClusterClient` examples
  go/api/base_client.go
  go/api/bitmap_commands_test.go
  go/api/connection_management_cluster_commands.go
  go/api/connection_management_cluster_commands_test.go
  go/api/connection_management_commands_test.go
  go/api/generic_cluster_commands_test.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/hash_commands_test.go
  go/api/hyperloglog_commands_test.go
  go/api/list_commands_test.go
  go/api/server_management_cluster_commands_test.go
  go/api/server_management_commands_test.go
  go/api/set_commands_test.go
  go/api/sorted_set_commands_test.go
  go/api/stream_commands_test.go
  go/api/string_commands_test.go
Labels: go

#3162 Java: Fix CD
  java/benchmarks/build.gradle
Labels: java, CI/CD

#3163 Node: Fix NPM CD tag on release-1.3
  .github/workflows/npm-cd.yml
  CHANGELOG.md
Labels: node, CI/CD

#3160 Go: Remove unneeded example file
  go/examples/examples.md
  go/examples/main.go
Labels: go

#3159 Update changelog for 1.3.0 release
  CHANGELOG.md
Labels: go

#3169 Go: Adding changes to `README` in release-1.3
  go/README.md
Labels: docs

#3138 Go: refactor options
  go/api/base_client.go
  go/api/bitmap_commands.go
  go/api/bitmap_commands_test.go
  go/api/generic_base_commands.go
  go/api/generic_base_commands_test.go
  go/api/hash_commands.go
  go/api/hash_commands_test.go
  go/api/list_commands.go
  go/api/list_commands_test.go
  go/api/options/bitfield_options.go
  go/api/options/command_options.go
  go/api/options/stream_options.go
  go/api/options/zinter_options.go
  go/api/options/zmpop_options.go
  go/api/set_commands.go
  go/api/set_commands_test.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/api/stream_commands.go
  go/api/stream_commands_test.go
  go/api/string_commands.go
  go/api/string_commands_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3168 Go: Update `README`
  go/README.md
Labels: go, docs

#3171 [Backport `1.3`] Go: Add Go CD approval (#3146)
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#3175 Update `README` for Go's current status
  README.md
Labels: docs

#3176 Refactor routes.
  go/api/base_client.go
  go/api/config/request_routing_config.go
  go/api/options/db_size_options.go
  go/api/request_routing_config_test.go
Labels: go

#3172 CI cleanup
  .github/workflows/scale-shr-test.yml
  .github/workflows/try-github-arm-runner.yml
Labels: CI/CD

#3178 Go: fix ld warnings on macos
  .github/workflows/go-cd.yml
  go/.cargo/config.toml
  go/api/errors/errors.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/response_handlers.go
Labels: go

#3183 Go/Quick CD fix
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#3184 Go: fix CD again
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#3182 Go: add known issues to readme
  go/README.md
Labels: go, docs

#2915 [redis-rs][core] Move connection refresh to the background
  glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
  glide-core/redis-rs/redis/src/cluster_async/mod.rs
  glide-core/redis-rs/redis/src/cluster_client.rs
  glide-core/redis-rs/redis/tests/support/mod.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
  glide-core/src/client/mod.rs
  python/python/tests/conftest.py
  python/python/tests/test_auth.py
Labels: Rust core, Core changes

#3107 Fix Node AzAffinity Flaky Test
  node/tests/GlideClusterClient.test.ts
Labels: node, testing, Flaky-tests

#3203 Go: fix modules test
  go/Makefile
Labels: CI/CD

#3106 Go: `XINFO GROUPS`.
  CHANGELOG.md
  go/api/base_client.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/stream_commands.go
  go/api/stream_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3078 Go: Add command ZInterCard
  CHANGELOG.md
  go/api/base_client.go
  go/api/options/zintercard_options.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3120 Go: `XINFO CONSUMERS`.
  CHANGELOG.md
  go/api/base_client.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/stream_commands.go
  go/api/stream_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3205 Python: Address `flake8` lint issues
  .github/workflows/python.yml
  Makefile
  benchmarks/python/python_benchmark.py
  examples/python/cluster_example.py
  examples/python/ft_example.py
  examples/python/json_example.py
  examples/python/standalone_example.py
  glide-core/redis-rs/get_command_info.py
  python/DEVELOPER.md
  python/python/glide/async_commands/cluster_commands.py
  python/python/glide/async_commands/command_args.py
  python/python/glide/async_commands/core.py
  python/python/glide/async_commands/server_modules/ft.py
  python/python/glide/async_commands/server_modules/ft_options/ft_aggregate_options.py
  python/python/glide/async_commands/server_modules/ft_options/ft_create_options.py
  python/python/glide/async_commands/server_modules/ft_options/ft_profile_options.py
  python/python/glide/async_commands/server_modules/ft_options/ft_search_options.py
  python/python/glide/async_commands/server_modules/glide_json.py
  python/python/glide/async_commands/server_modules/json_batch.py
  python/python/glide/async_commands/sorted_set.py
  python/python/glide/async_commands/standalone_commands.py
  python/python/glide/async_commands/stream.py
  python/python/glide/async_commands/transaction.py
  python/python/glide/config.py
  python/python/glide/constants.py
  python/python/glide/glide_client.py
  python/python/glide/protobuf_codec.py
  python/python/glide/routes.py
  python/python/tests/test_api_export.py
  python/python/tests/test_async_client.py
  python/python/tests/test_auth.py
  python/python/tests/test_config.py
  python/python/tests/test_pubsub.py
  python/python/tests/test_read_from_strategy.py
  python/python/tests/test_scan.py
  python/python/tests/test_transaction.py
  python/python/tests/test_utils.py
  python/python/tests/tests_server_modules/test_ft.py
  python/python/tests/tests_server_modules/test_json.py
  python/python/tests/utils/cluster.py
  python/python/tests/utils/utils.py
  utils/get_licenses_from_ort.py
  utils/release-candidate-testing/python/rc_test.py
Labels: python

#3214 Python: Added verbose test flag for `pytest`
  .github/workflows/python.yml
  Makefile
  python/DEVELOPER.md
  python/python/tests/conftest.py
Labels: python, testing

#3212 Go: Fix flaky test.
  go/integTest/cluster_commands_test.go
Labels: go, testing

#3206 Go: Add licence header check.
  go/.gitignore
  go/Makefile
  go/api/generic_cluster_commands_test.go
  go/api/options/db_size_options.go
  go/api/server_management_cluster_commands_test.go
  go/benchmarks/main.go
Labels: go, CI/CD

#3140 Go: Add command zlexcount
  CHANGELOG.md
  go/api/base_client.go
  go/api/options/zrange_options.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3221 Go: Remove -race flag on go test
  go/Makefile
Labels: go, testing

#3227 Suppress CI failure
  deny.toml
Labels: CI/CD, dependency

#3213 Add source distribution upload to the PyPi-cd workflow
  .github/workflows/pypi-cd.yml
Labels: python, CI/CD

#3232 Go: fixing cross slot error in ZINTERCARD examples
  CHANGELOG.md
  go/api/sorted_set_commands_test.go
Labels: go, testing

#3253 Go: Remove -race flag on go test [release-1.3]
  go/Makefile
Labels: go, testing

#3249 Fix ORT CI.
  .github/workflows/ort.yml
Labels: CI/CD

#3255 Python: Temporarily suppress rust linter warnings
  python/src/lib.rs
Labels: python

#3220 Python: Added skip markers to tests
  python/python/tests/test_async_client.py
  python/python/tests/test_transaction.py
Labels: python, testing

#3231 Go: X86_64 macOS support for developers
  go/Makefile
  go/api/base_client.go
Labels: go

#3254 Python: Cache server version
  python/python/tests/utils/utils.py
Labels: python, testing

#3245 C#: Fix tests logging.
  csharp/tests/tests.csproj
  csharp/tests/xunit.runner.json
Labels: C#, testing

#3247 C#: Remove `Redis` references.
  csharp/lib/src/lib.rs
  csharp/tests/Integration/IntegrationTestBase.cs
Labels: C#

#3208 Go: Fix channel passing from Go to Rust by using `runtime.Pinner` or `cgo.Handle`
  CHANGELOG.md
  go/api/base_client.go
  go/api/pinner.go
  go/api/pinner_old.go
  go/api/pinner_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/parallelized_test.go
Labels: go

#3223 C#: Fix build on windows.
  csharp/lib/glide.csproj
Labels: C#, windows

#3270 [Backport to Release 1.3.1] Go: Fix channel passing from Go to Rust by using `runtime.Pinner` or …
  CHANGELOG.md
  go/api/base_client.go
  go/api/pinner.go
  go/api/pinner_old.go
  go/api/pinner_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/parallelized_test.go
Labels: go

#3272 Go: Update Go versions used in CI
  .github/json_matrices/supported-languages-versions.json
  .github/workflows/go-cd.yml
  .github/workflows/go.yml
  go/Makefile
Labels: go, CI/CD

#3279 Updated README
  README.md
  go/README.md
Labels: docs

#3115 Go: JSON.SET and JSON.GET command added
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/response_types.go
  go/api/server-modules/glidejson/example_utils.go
  go/api/server-modules/glidejson/json_commands.go
  go/api/server-modules/glidejson/json_commands_test.go
  go/api/server-modules/glidejson/options/json_get_options.go
  go/api/server-modules/glidejson/options/json_set_options.go
  go/integTest/json_module_test.go
Labels: go

#3258 Go: Fix doc for `ZPopMinWithOptions`
  go/api/base_client.go
Labels: go, docs

#3236 Go: fix data race on the coreClient with `sync.Mutex` and a channel map
  CHANGELOG.md
  go/api/base_client.go
  go/integTest/shared_commands_test.go
Labels: go

#3292 [Backport to release-1.3] Go: fix data race on the coreClient with `sync.Mutex` and a channel m…
  CHANGELOG.md
  go/api/base_client.go
  go/integTest/shared_commands_test.go
Labels: go
