Repository valkey-io/valkey-glide, pull requests merged in 2025-01, with the labels that each got.

#2838 Go: add ZCARD
  CHANGELOG.md
  go/api/base_client.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2879 fix gradle
  java/benchmarks/build.gradle
  java/client/build.gradle
  java/integTest/build.gradle
Labels: java

#2894 Remove `git submodule update` from DEVELOPER.md
  csharp/DEVELOPER.md
  go/DEVELOPER.md
Labels: docs

#2844 Go: Fix command groups and links
  go/api/connection_management_commands.go
  go/api/generic_commands.go
  go/api/hash_commands.go
  go/api/list_commands.go
  go/api/set_commands.go
  go/api/string_commands.go
Labels: go, docs

#2864 Cleanup unused CI file
  python/.github/workflows/CI.yml
Labels: python, CI/CD

#2849 GO: Add BZPopMin command
  CHANGELOG.md
  go/api/base_client.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2917 Go: Add `HScan` command
  CHANGELOG.md
  go/api/base_client.go
  go/api/command_options.go
  go/api/hash_commands.go
  go/api/options/base_scan_options.go
  go/api/options/constants.go
  go/api/options/hscan_options.go
  go/api/set_commands.go
  go/integTest/shared_commands_test.go
  go/integTest/test_utils.go
Labels: go

#2421 [1.1] Update protoc
  .github/workflows/install-rust-and-protoc/action.yml
  .github/workflows/java-cd.yml
  .github/workflows/java.yml
  .github/workflows/pypi-cd.yml
  CHANGELOG.md
  java/DEVELOPER.md
  java/client/build.gradle
  python/DEVELOPER.md
  python/requirements.txt
Labels: dependency

#2829 Go: Implement Persist Command
  go/api/base_client.go
  go/api/generic_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2929 Fix value conversion for `CONFIG GET`. (#2381)
  CHANGELOG.md
  glide-core/src/client/value_conversion.rs
Labels: Rust core

#2926 Node: Fix `zrangeWithScores` (disallow `RangeByLex` as it is not supported)
  CHANGELOG.md
  node/src/BaseClient.ts
  node/src/Transaction.ts
Labels: node

#2919 Update CONFIG GET and CONFIG SET documentation and tests
  CHANGELOG.md
  java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
  java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
  java/client/src/main/java/glide/api/models/BaseTransaction.java
  java/integTest/src/test/java/glide/TransactionTestUtilities.java
  node/src/GlideClient.ts
  node/src/GlideClusterClient.ts
  node/src/Transaction.ts
  node/tests/GlideClusterClient.test.ts
  node/tests/SharedTests.ts
  python/python/glide/async_commands/cluster_commands.py
  python/python/glide/async_commands/standalone_commands.py
  python/python/glide/async_commands/transaction.py
  python/python/tests/test_async_client.py
  python/python/tests/test_transaction.py
Labels: docs

#2932 Go: Add command ZRank and ZRevRank
  go/api/base_client.go
  go/api/options/constants.go
  go/api/response_handlers.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2933 Fixed minor documentation typos.
  python/DEVELOPER.md
  python/python/glide/async_commands/core.py
Labels: docs

#2925 Go: ZRANGE
  go/api/base_client.go
  go/api/options/zrange_options.go
  go/api/sorted_set_commands.go
  go/integTest/glide_test_suite_test.go
  go/integTest/shared_commands_test.go
Labels: go

#2383 Java: Add RESP2 support
  CHANGELOG.md
  java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/ProtocolVersion.java
  java/client/src/main/java/glide/managers/ConnectionManager.java
  java/client/src/test/java/glide/managers/ConnectionManagerTest.java
  java/integTest/src/test/java/glide/ConnectionTests.java
  java/integTest/src/test/java/glide/PubSubTests.java
  java/integTest/src/test/java/glide/SharedCommandTests.java
  java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
  java/integTest/src/test/java/glide/cluster/CommandTests.java
  java/integTest/src/test/java/glide/standalone/CommandTests.java
  java/integTest/src/test/java/glide/standalone/TransactionTests.java
  node/src/BaseClient.ts
  python/python/glide/config.py
Labels: java

#2909 SET IFEQ command implemented in node + tests
  CHANGELOG.md
  node/src/BaseClient.ts
  node/src/Commands.ts
  node/tests/SharedTests.ts
Labels: node

#2916 Node: refactor writeOrBufferCommandRequest (#2675)
  node/src/BaseClient.ts
  node/src/GlideClusterClient.ts
Labels: node, Optimization

#2939 Go: Fix return types, part 1: `int64` instead of `Result[int64]`
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/hash_commands.go
  go/api/hyperloglog_commands.go
  go/api/list_commands.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/api/stream_commands.go
  go/api/string_commands.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#2941 Go: Fix return types, part 2: `float64` instead of `Result[float64]` and bool
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/hash_commands.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/api/string_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2942 Go: Fix return types, part 3: `string` instead of `Result[string]`
  go/api/base_client.go
  go/api/glide_client.go
  go/api/list_commands.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/server_management_commands.go
  go/api/string_commands.go
  go/benchmarks/glide_benchmark_client.go
  go/examples/main.go
  go/integTest/glide_test_suite_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#2940 Fix `cluster_manager` script
  utils/cluster_manager.py
Labels: CI/CD

#2944 Go: XDel command added
  go/api/base_client.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2930 Go: Add Zcount command
  go/api/base_client.go
  go/api/options/zcount_options.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2882 Go: `XREAD`.
  go/api/base_client.go
  go/api/options/stream_options.go
  go/api/response_handlers.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
  go/utils/transform_utils.go
Labels: go

#2950 Go: Add command ZScan
  go/api/base_client.go
  go/api/options/constants.go
  go/api/options/zscan_options.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2957 GO: xpending command
  go/Makefile
  go/api/base_client.go
  go/api/options/stream_options.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2781 GO Implement Dump, Restore and ObjectEncoding Command
  go/api/base_client.go
  go/api/command_options.go
  go/api/generic_base_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2863 GO: Implement Echo Command
  go/api/base_client.go
  go/api/connection_management_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2949 Go: `XREADGROUP`.
  go/api/base_client.go
  go/api/options/stream_options.go
  go/api/response_handlers.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2931 Java: Shadow protobuf dependency
  .github/workflows/ort.yml
  CHANGELOG.md
  java/benchmarks/build.gradle
  java/build.gradle
  java/client/build.gradle
  java/integTest/build.gradle
Labels: java, dependency

#2967 Go: Add commands ZRemRangeByRank/ZRemRangeByScore/ZRemRangeByLex
  go/api/base_client.go
  go/api/options/zrange_options.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2955 Go: XAUTOCLAIM.
  go/api/base_client.go
  go/api/options/stream_options.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2956 Go: update return types & response handlers for scan commands
  go/api/base_client.go
  go/api/hash_commands.go
  go/api/response_handlers.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
  go/integTest/test_utils.go
Labels: go

#2958 Go implement object freq object idle object ref count command
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2888 Go: Implement Sort, Sort ReadOnly and Sort Store commands
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/options/sort_options.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#2966 Go: `XGROUP CREATE`.
  go/api/base_client.go
  go/api/options/stream_options.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2965 Go: Fix return types, part 6
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/hash_commands.go
  go/api/list_commands.go
  go/api/response_handlers.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2964 Go: Fix return types, parn 5
  go/api/base_client.go
  go/api/glide_client.go
  go/api/hash_commands.go
  go/api/list_commands.go
  go/api/response_handlers.go
  go/api/server_management_commands.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#2976 Go: `XGROUP SETID`.
  go/api/base_client.go
  go/api/options/stream_options.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2977 Go: `HRANDFIELD`.
  go/api/base_client.go
  go/api/hash_commands.go
  go/api/options/constants.go
  go/api/response_handlers.go
  go/integTest/shared_commands_test.go
Labels: go

#2918 Go: Implement GetBit, SetBit, BitCount and Wait commands
  go/api/base_client.go
  go/api/bitmap_commands.go
  go/api/generic_base_commands.go
  go/api/options/bitcount_options.go
  go/integTest/shared_commands_test.go
Labels: go

#2962 Implemented IFEQ set command in python with tests
  CHANGELOG.md
  python/python/glide/__init__.py
  python/python/glide/async_commands/core.py
  python/python/tests/test_async_client.py
Labels: python, Feature

#2987 ORT- Add resolutions for hybrid-node-tests and bump versions
  .github/workflows/ort.yml
  node/.ort.yml
Labels: CI/CD

#2991 Go: Implement Server Management Command DBSize
  go/api/glide_client.go
  go/api/server_management_commands.go
  go/integTest/standalone_commands_test.go
Labels: go

#2980 GO: Implement Copy Command
  go/api/base_client.go
  go/api/command_options.go
  go/api/generic_base_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2981 Moved documentation comments to base_client file and made changes to GlideClient for pkgsite to work
  go/api/base_client.go
  go/api/connection_management_commands.go
  go/api/generic_base_commands.go
  go/api/generic_cluster_commands.go
  go/api/generic_commands.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/hash_commands.go
  go/api/hyperloglog_commands.go
  go/api/list_commands.go
  go/api/server_management_commands.go
  go/api/set_commands.go
  go/api/sorted_set_commands.go
  go/api/stream_commands.go
  go/api/string_commands.go
  go/integTest/glide_test_suite_test.go
  go/integTest/shared_commands_test.go
Labels: go, docs

#3000 quickfix of changing glideClient to become GlideClient
  go/api/glide_client.go
Labels: go

#2989 Go: Add command XRange and XRevRange
  go/api/base_client.go
  go/api/options/constants.go
  go/api/options/stream_options.go
  go/api/options/zrange_options.go
  go/api/response_handlers.go
  go/api/stream_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2996 Go: Added config folder for request_routing_config_test.go and errors folder for errors.go
  go/api/base_client.go
  go/api/command_options.go
  go/api/config/request_routing_config.go
  go/api/errors/errors.go
  go/api/response_handlers.go
  go/integTest/connection_test.go
  go/integTest/request_routing_config_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3003 Java: Add os-maven-plugin example to README
  java/README.md
Labels: java, docs

#2999 Go: Implement Bitfield and Bitfield ReadOnly commands
  go/api/base_client.go
  go/api/bitmap_commands.go
  go/api/glide_client.go
  go/api/options/bitfield_options.go
  go/api/response_handlers.go
  go/integTest/shared_commands_test.go
Labels: go

#2988 Go: `INFO`.
  go/api/command_options.go
  go/api/config/request_routing_config.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/response_types.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_commands.go
  go/integTest/cluster_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/json_module_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/vss_module_test.go
Labels: go

#3019 PYTHON: Add Python package description
  python/pyproject.toml
Labels: python

#3025 Java: Fix lpopCount null handling
  CHANGELOG.md
  java/client/src/main/java/glide/api/BaseClient.java
  java/integTest/src/test/java/glide/SharedCommandTests.java
  java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java
Labels: java

#2963 Go: Implement Time Command
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/options/route_options.go
  go/api/response_handlers.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_commands.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3007 Go: `BZMPop`
  go/api/base_client.go
  go/api/command_options.go
  go/api/options/zmpop_options.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2995 Go: Implement DBSize Server Management Cluster
  go/api/glide_cluster_client.go
  go/api/options/db_size_options.go
  go/api/options/route_options.go
  go/api/server_management_cluster_commands.go
  go/integTest/cluster_commands_test.go
Labels: go

#3008 Go: `ZMSCORE`.
  go/api/base_client.go
  go/api/response_handlers.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#2983 Go: `ZRANDMEMBER`.
  go/api/base_client.go
  go/api/options/constants.go
  go/api/response_handlers.go
  go/api/response_types.go
  go/api/sorted_set_commands.go
  go/integTest/shared_commands_test.go
Labels: go

#3001 Java: updating error message in thread pool supplier
  java/client/src/main/java/glide/connectors/resources/Platform.java
Labels: java

#2993 Go: Implement Echo Connection Management Cluster
  go/api/connection_management_cluster_commands.go
  go/api/glide_cluster_client.go
  go/api/options/echo_options.go
  go/integTest/cluster_commands_test.go
Labels: go
