Repository valkey-io/valkey-glide, pull requests merged in 2025-06, with the labels that each got.

#4047 Go: Add String Batch Tests
  go/integTest/batch_test.go
Labels: go

#4033 Go: Add Set Commands Batch Tests
  go/integTest/batch_test.go
  go/pipeline/base_batch.go
Labels: go

#4025 Go: PubSub Batch Tests
  go/integTest/batch_test.go
Labels: go

#4036 Go: Add Sorted Set Batch Tests
  go/integTest/batch_test.go
  go/pipeline/base_batch.go
Labels: go

#4067 Go: cleanup CommandResponses after context cancellation/timeout
  go/base_client.go
  go/glide_cluster_client.go
  go/integTest/PubSubGoTestPlan.md
Labels: go

#4003 Go: Connection Management Batch Tests
  go/glide_cluster_client.go
  go/integTest/batch_test.go
Labels: go

#3886 Go: Clean up most panics in FFI layer
  ffi/Cargo.toml
  ffi/src/lib.rs
  ffi/tests/ffi_client_tests.rs
  glide-core/redis-rs/redis/src/types.rs
  go/options/script_options.go
Labels: go, Rust

#4054 Go: `WATCH` and `UNWATCH`
  CHANGELOG.md
  go/base_client.go
  go/batch_test.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/integTest/batch_test.go
  go/integTest/glide_test_suite_test.go
  go/internal/interfaces/client_interfaces.go
  go/response_handlers.go
Labels: go

#4032 Go: Function Commands Batch Tests
  go/integTest/batch_test.go
  go/pipeline/base_batch.go
Labels: go

#3932 Go: Add otel support
  .github/workflows/go.yml
  CHANGELOG.md
  ffi/src/lib.rs
  ffi/tests/ffi_client_tests.rs
  go/Makefile
  go/base_client.go
  go/integTest/glide_test_suite_test.go
  go/integTest/opentelemetry_test.go
  go/opentelemetry.go
Labels: go, Telemetry

#4078 Go: OTel doc update
  go/base_client.go
  go/integTest/glide_test_suite_test.go
  go/integTest/opentelemetry_test.go
  go/opentelemetry.go
Labels: go, Telemetry

#4079 Go: Fix Full Matrix Tests
  go/integTest/batch_test.go
  go/integTest/cluster_commands_test.go
Labels: go, testing

#4085 Go: XRead and XReadGroup response update
  CHANGELOG.md
  go/base_client.go
  go/integTest/batch_test.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/stream_commands.go
  go/models/stream_command_results.go
  go/pipeline/base_batch.go
  go/response_handlers.go
  go/stream_commands_test.go
Labels: go

#4095 Go: free endpoint cstrings in otel config
  go/opentelemetry.go
Labels: go

#4088 Go: Fix `ClientGetName` and `ClientSetName`
  CHANGELOG.md
  go/connection_management_cluster_commands_test.go
  go/connection_management_commands_test.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
  go/internal/interfaces/connection_management_cluster_commands.go
  go/internal/interfaces/connection_management_commands.go
  go/response_handlers.go
Labels: go

#4086 Go: Change Blocking Commands to use `time.Duration`
  CHANGELOG.md
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/list_commands.go
  go/internal/interfaces/sorted_set_commands.go
  go/list_commands_test.go
  go/options/stream_options.go
  go/pipeline/base_batch.go
  go/sorted_set_commands_test.go
Labels: go

#4101 Go: Fix `GeoHash` Return Type to include Nillable Strings
  CHANGELOG.md
  go/base_client.go
  go/geospacial_commands_test.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/geospacial_commands.go
  go/pipeline/base_batch.go
Labels: go

#4084 Java: fix addReturnField in FT.search
  CHANGELOG.md
  java/client/src/main/java/glide/api/models/commands/FT/FTSearchOptions.java
  java/integTest/src/test/java/glide/modules/VectorSearchTests.java
Labels: java

#4100 Remove unused tls crates
  glide-core/Cargo.toml
  glide-core/redis-rs/redis/Cargo.toml
  glide-core/redis-rs/redis/src/aio/connection.rs
  glide-core/redis-rs/redis/src/aio/mod.rs
  glide-core/redis-rs/redis/src/aio/tokio.rs
  glide-core/redis-rs/redis/src/client.rs
  glide-core/redis-rs/redis/src/cluster.rs
  glide-core/redis-rs/redis/src/cluster_client.rs
  glide-core/redis-rs/redis/src/connection.rs
  glide-core/redis-rs/redis/src/lib.rs
  glide-core/redis-rs/redis/src/types.rs
  glide-core/redis-rs/redis/tests/support/cluster.rs
  glide-core/redis-rs/redis/tests/support/mod.rs
  glide-core/redis-rs/redis/tests/test_async.rs
  glide-core/redis-rs/redis/tests/test_cluster.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
Labels: Optimization, dependencies, Rust

#4119 Allow scheduling of full matrix tests for different branches
  .github/workflows/full-matrix-tests-sweeper.yml
  .github/workflows/full-matrix-tests.yml
Labels: CI/CD, testing

#4121 Add explicit run-modules-tests parameter to workflow_dispatch trigger of CI tests
  .github/workflows/full-matrix-tests-sweeper.yml
  .github/workflows/full-matrix-tests.yml
  .github/workflows/go.yml
  .github/workflows/java.yml
  .github/workflows/node.yml
  .github/workflows/python.yml
Labels: CI/CD, testing

#4103 Go: Use errors idiomatically
  CHANGELOG.md
  go/.gitignore
  go/base_client.go
  go/callbacks.go
  go/config/config_test.go
  go/config/request_routing_config.go
  go/constants/constants.go
  go/errors.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/integTest/batch_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/connection_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/vss_module_test.go
  go/internal/errors/errors.go
  go/internal/utils/transform_utils.go
  go/opentelemetry.go
  go/options/bitop_options.go
  go/options/command_options.go
  go/pipeline/base_batch.go
  go/pipeline/batch.go
  go/response_handlers.go
Labels: go

#4123 Fix build issue: resolve assertions
  go/config/config_test.go
  go/integTest/shared_commands_test.go
Labels: go

#4130 Go: Fix single node route for batch
  go/base_client.go
  go/config/request_routing_config.go
  go/pipeline/batch.go
Labels: go

#4150 fix: resolve broken ffi path
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#4141 Fix XAdd return type with no optional args
  CHANGELOG.md
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/stream_commands.go
  go/stream_commands_test.go
Labels: go

#4104 Go: Response converters for batch
  go/base_client.go
  go/constants/constants.go
  go/integTest/batch_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/shared_commands_test.go
  go/internal/cmd.go
  go/internal/converter_helpers.go
  go/internal/converters.go
  go/models/response_types.go
  go/options/command_options.go
  go/options/hscan_options.go
  go/options/zscan_options.go
  go/pipeline/base_batch.go
  go/pipeline/batch.go
  go/pipeline/batch_options.go
  go/response_handlers.go
Labels: go

#4151 Broken FFI artifact on Linux builds
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#4152 fix: resolve broken ffi path
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#4137 Python: fix flaky Open Telemetry memory checks
  python/tests/test_opentelemetry.py
Labels: python, Flaky-tests

#4145 Fix `LREM` Count Parameter Docs
  go/base_client.go
  go/pipeline/base_batch.go
  java/client/src/main/java/glide/api/commands/ListBaseCommands.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
  node/src/BaseClient.ts
  node/src/Batch.ts
  python/python/glide/async_commands/batch.py
  python/python/glide/async_commands/core.py
Labels: python, node, java, go, docs

#4128 Java: Change Response Handler for `xpending`
  java/client/src/main/java/glide/api/BaseClient.java
Labels: java

#4140 Go: Add Rest of Batch Tests
  go/integTest/batch_test.go
Labels: go, testing

#4126 Go: Fix `LRange` Docs Return Type
  java/client/src/main/java/glide/api/BaseClient.java
Labels: java, go, docs

#4136 Go: XInfoStream update response
  CHANGELOG.md
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/stream_commands.go
  go/models/response_types.go
  go/models/stream_command_results.go
  go/response_handlers.go
  go/stream_commands_test.go
Labels: go

#4185 Go: XInfoStream example fix
  CHANGELOG.md
  go/stream_commands_test.go
Labels: go, docs, testing

#4184 Fix `SCRIPT SHOW` in batch test.
  go/integTest/batch_test.go
Labels: go, testing

#4106 Go: Remove Pointers for Options Args
  CHANGELOG.md
  go/base_client.go
  go/integTest/batch_test.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/sorted_set_commands.go
  go/internal/interfaces/stream_commands.go
  go/options/zunion_options.go
  go/sorted_set_commands_test.go
  go/stream_commands_test.go
Labels: go

#4186 Go: Fix batch examples.
  go/batch_test.go
Labels: go, docs, testing

#4190 Go: Fix `ZAddIncr` Return Type
  CHANGELOG.md
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/interfaces/sorted_set_commands.go
  go/sorted_set_commands_test.go
Labels: go

#4179 Go: Smart object for scan response
  ffi/src/lib.rs
  go/base_client.go
  go/generic_cluster_commands_test.go
  go/generic_commands_test.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/hash_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/context_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
  go/internal/converters.go
  go/internal/interfaces/generic_cluster_commands.go
  go/internal/interfaces/generic_commands.go
  go/internal/interfaces/hash_commands.go
  go/internal/interfaces/set_commands.go
  go/internal/interfaces/sorted_set_commands.go
  go/models/scan.go
  go/options/cluster_scan_options.go
  go/response_handlers.go
  go/set_commands_test.go
  go/sorted_set_commands_test.go
Labels: go

#4189 Go: Fix Linking to Other Commands in Docs
  go/base_client.go
  go/config/config.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/pipeline/base_batch.go
Labels: go, docs

#4163 Fix tls
  deny.toml
  glide-core/Cargo.toml
  glide-core/redis-rs/redis/Cargo.toml
  glide-core/redis-rs/redis/src/aio/connection.rs
  glide-core/redis-rs/redis/src/aio/mod.rs
  glide-core/redis-rs/redis/src/aio/tokio.rs
  glide-core/redis-rs/redis/src/client.rs
  glide-core/redis-rs/redis/src/cluster.rs
  glide-core/redis-rs/redis/src/cluster_async/mod.rs
  glide-core/redis-rs/redis/src/cluster_client.rs
  glide-core/redis-rs/redis/src/cluster_slotmap.rs
  glide-core/redis-rs/redis/src/connection.rs
  glide-core/redis-rs/redis/src/lib.rs
  glide-core/redis-rs/redis/src/types.rs
  glide-core/redis-rs/redis/tests/support/cluster.rs
  glide-core/redis-rs/redis/tests/support/mod.rs
  glide-core/redis-rs/redis/tests/test_async.rs
  glide-core/redis-rs/redis/tests/test_cluster.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
  utils/get_licenses_from_ort.py
Labels: bug, Release blocker, Rust

#3469 Update Go Ort
  .github/workflows/ort.yml
  .github/workflows/run-ort-tools/action.yml
  CHANGELOG.md
  ffi/.ort.yml
  go/.ort.yml
  go/THIRD_PARTY_LICENSES_GO
Labels: go, CI/CD

#4166 Go: Update return type for LMPop and related commands
  CHANGELOG.md
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/converter_helpers.go
  go/internal/converters.go
  go/internal/interfaces/list_commands.go
  go/list_commands_test.go
  go/models/response_types.go
  go/response_handlers.go
Labels: go

#4188 Go: Fix collision in option types.
  go/config/request_routing_config.go
  go/options/bitfield_options.go
  go/options/geosearch_options.go
  go/options/zrange_options.go
Labels: go

#4195 Fix `LTRIM` Docs
  go/base_client.go
  go/pipeline/base_batch.go
  java/client/src/main/java/glide/api/commands/ListBaseCommands.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
  node/src/BaseClient.ts
  node/src/Batch.ts
  python/python/glide/async_commands/batch.py
  python/python/glide/async_commands/core.py
Labels: python, node, java, go, docs

#4183 Go: XInfoStream with full options
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/converter_helpers.go
  go/internal/interfaces/stream_commands.go
  go/models/response_types.go
  go/response_handlers.go
  go/stream_commands_test.go
Labels: go

#4187 Go: Return strongly typed object for LCS commands
  CHANGELOG.md
  go/base_client.go
  go/integTest/shared_commands_test.go
  go/internal/cmd.go
  go/internal/converter_helpers.go
  go/internal/interfaces/string_commands.go
  go/models/response_types.go
  go/response_handlers.go
  go/string_commands_test.go
Labels: go

#4197 Go: Update README
  go/README.md
  go/config/config.go
Labels: docs

#4205 Node: fix examples
  node/src/BaseClient.ts
Labels: node

#4217 Go: Fix `LInsert` `insertPosition` Docs
  go/base_client.go
Labels: go, docs

#4240 Java: Fix Incorrect `XRANGE` `XREVRANGE` Return Docs
  java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
Labels: java, docs

#4216 Go: Update examples link
  go/examples/examples.md
Labels: go

#4238 Go: Add Package Comments
  go/config/doc.go
  go/constants/constants.go
  go/integTest/doc.go
  go/models/doc.go
  go/options/doc.go
  go/options/zintercard_options.go
  go/options/zunion_options.go
  go/pipeline/doc.go
Labels: go, docs

#4203 C#: Update docs in FFI layer.
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
Labels: C#, docs

#4229 CI: Run fill matrix on main.
  .github/workflows/full-matrix-tests-sweeper.yml
Labels: CI/CD

#4244 Go: Update examples links
  go/examples/examples.md
Labels: go

#4247 C#: Fix a test.
  csharp/tests/Valkey.Glide.IntegrationTests/SharedBatchTests.cs
Labels: C#, testing

#4227 C#: Fix `dotnet` Docs
  csharp/DEVELOPER.md
Labels: C#

#4267 Node: Validate clientAZ when using AZ affinity strategies
  CHANGELOG.md
  node/src/BaseClient.ts
Labels: node
