Repository valkey-io/valkey-glide, pull requests merged in 2025-03, with the labels that each got.

#3296 Go: Update Go versions used in CI [release-1.3]
  .github/json_matrices/supported-languages-versions.json
  .github/workflows/go-cd.yml
  .github/workflows/go.yml
  go/Makefile
Labels: go, CI/CD

#3262 Update readme - include compatibility notice
  README.md
Labels: docs

#3283 C#: Reorganize client structure.
  benchmarks/csharp/Program.cs
  csharp/lib/BaseClient.cs
  csharp/lib/Commands/IConnectionManagementCommands.cs
  csharp/lib/Commands/IStringBaseCommands.cs
  csharp/lib/GlideClient.cs
  csharp/lib/Internals/Message.cs
  csharp/lib/Internals/MessageContainer.cs
  csharp/tests/Integration/GetAndSet.cs
Labels: C#

#3235 Go: Add AzAffinity Support
  CHANGELOG.md
  go/api/base_client.go
  go/api/config.go
  go/api/config_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/readfrom_strategy_test.go
Labels: go

#3290 Go: adding advanced client configs & connectionTimeout
  CHANGELOG.md
  go/api/config.go
  go/integTest/connection_test.go
  go/integTest/glide_test_suite_test.go
Labels: go

#3225 Go: randomize cluster ports for Example tests
  .github/workflows/go.yml
  go/DEVELOPER.md
  go/Makefile
  go/api/example_utils.go
  go/api/string_commands_test.go
Labels: go, testing

#3295 Go: Implemented Cluster Scan
  CHANGELOG.md
  go/api/generic_cluster_commands.go
  go/api/generic_cluster_commands_test.go
  go/api/glide_cluster_client.go
  go/api/options/cluster_scan_options.go
  go/api/options/constants.go
  go/integTest/cluster_commands_test.go
  go/src/lib.rs
Labels: go

#3331 Make redis-rs CI workflow fail correclty in case of tests failure
  .github/workflows/redis-rs.yml
Labels: CI/CD, testing

#3273 C#: IT with shared client
  csharp/lib/BaseClient.cs
  csharp/lib/Internals/Message.cs
  csharp/lib/glide.csproj
  csharp/tests/Integration/GetAndSet.cs
  csharp/tests/Integration/SharedClientTests.cs
  csharp/tests/Integration/SharedCommandTests.cs
  csharp/tests/Integration/TestConfiguration.cs
  csharp/tests/Usings.cs
  csharp/tests/tests.csproj
Labels: C#, testing

#3319 Revert "Update readme - include compatibility notice"
  README.md
Labels: docs

#3316 Python: Fix clippy useless conversion errors
  python/Cargo.toml
  python/src/lib.rs
Labels: python

#2352 Java: move pubsub IT to another suite
  .github/workflows/java.yml
  java/DEVELOPER.md
  java/integTest/build.gradle
Labels: java, testing

#3324 Replacing Hash Maps in response handling with LinkedHashMap
  CHANGELOG.md
  java/client/src/main/java/glide/api/BaseClient.java
  java/client/src/main/java/glide/api/GlideClusterClient.java
  java/client/src/main/java/glide/ffi/resolvers/StatisticsResolver.java
  java/client/src/main/java/glide/utils/ArrayTransformUtils.java
  java/integTest/src/test/java/glide/TestUtilities.java
Labels: java

#2861 Core: Extract `proto` from `socket-layer` feature.
  .gitignore
  glide-core/Cargo.toml
  glide-core/build.rs
  glide-core/src/client/types.rs
  glide-core/src/lib.rs
  glide-core/src/request_type.rs
  glide-core/src/retry_strategies.rs
  go/Cargo.toml
  go/src/lib.rs
Labels: Rust core

#3343 Java: Fix version check in IT/MT startup.
  java/integTest/build.gradle
  java/integTest/src/test/java/glide/TestConfiguration.java
Labels: java, CI/CD

#3345 Go: Add push tag trigger to CD
  .github/workflows/go-cd.yml
Labels: go, CI/CD

#3349 Move ServerError into Value
  glide-core/redis-rs/redis-test/src/lib.rs
  glide-core/redis-rs/redis/src/aio/connection.rs
  glide-core/redis-rs/redis/src/aio/multiplexed_connection.rs
  glide-core/redis-rs/redis/src/cluster.rs
  glide-core/redis-rs/redis/src/cluster_async/pipeline_routing.rs
  glide-core/redis-rs/redis/src/cluster_pipeline.rs
  glide-core/redis-rs/redis/src/connection.rs
  glide-core/redis-rs/redis/src/parser.rs
  glide-core/redis-rs/redis/src/pipeline.rs
  glide-core/redis-rs/redis/src/types.rs
  glide-core/redis-rs/redis/tests/parser.rs
  glide-core/redis-rs/redis/tests/support/mock_cluster.rs
  glide-core/redis-rs/redis/tests/support/mod.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
  glide-core/src/client/value_conversion.rs
  glide-core/tests/utilities/mod.rs
  java/src/lib.rs
  node/rust-client/src/lib.rs
  python/src/lib.rs
Labels: Core changes

#2906 Safer wrapping for FFI clients.
  csharp/lib/src/lib.rs
  go/src/lib.rs
Labels: C#, go

#3336 Python: Added `sphinx` for documentation
  .github/workflows/python.yml
  python/.gitignore
  python/DEVELOPER.md
  python/dev_requirements.txt
  python/docs/Makefile
  python/docs/conf.py
  python/docs/index.rst
  python/docs/make.bat
  python/python/glide/async_commands/bitmap.py
  python/python/glide/async_commands/cluster_commands.py
  python/python/glide/async_commands/command_args.py
  python/python/glide/async_commands/core.py
  python/python/glide/async_commands/sorted_set.py
  python/python/glide/async_commands/standalone_commands.py
  python/python/glide/async_commands/stream.py
  python/python/glide/async_commands/transaction.py
  python/python/glide/config.py
  python/python/glide/logger.py
  python/python/glide/protobuf_codec.py
  python/python/glide/routes.py
  python/python/tests/conftest.py
  python/python/tests/test_pubsub.py
Labels: python, docs

#3356 Disable Flaky Tests
  java/integTest/src/test/java/glide/cluster/ClusterClientTests.java
  java/integTest/src/test/java/glide/cluster/CommandTests.java
  java/integTest/src/test/java/glide/standalone/CommandTests.java
  node/tests/GlideClient.test.ts
  node/tests/TestUtilities.ts
Labels: node, java, Flaky-tests

#3252 C#: Rework linters/analyzers approach
  .github/workflows/csharp.yml
  csharp/DEVELOPER.md
  csharp/csharp.sln
  csharp/lib/glide.csproj
  csharp/tests/tests.csproj
Labels: C#, CI/CD

#3335 C#: Custom command for standalone client.
  csharp/lib/BaseClient.cs
  csharp/lib/Commands/IGenericCommands.cs
  csharp/lib/Commands/IStringBaseCommands.cs
  csharp/lib/GlideClient.cs
  csharp/lib/Internals/Message.cs
  csharp/lib/Internals/MessageContainer.cs
  csharp/lib/src/lib.rs
  csharp/tests/Integration/StadaloneClientTests.cs
Labels: C#

#3366 Add command GeoAdd and the geospatial command interface
  CHANGELOG.md
  go/api/base_client.go
  go/api/example_utils.go
  go/api/geospacial_commands.go
  go/api/geospacial_commands_test.go
  go/api/options/constants.go
  go/api/options/geoadd_options.go
  go/api/options/zadd_options.go
  go/integTest/shared_commands_test.go
Labels: go

#3351 Go: fix unsafe precondition violation for slice::from_raw_parts
  CHANGELOG.md
  go/src/lib.rs
Labels: go

#3361 Node: Fix `xpendingWithOptions` Flaky Test
  node/tests/TestUtilities.ts
Labels: node, testing, Flaky-tests

#3347 C#: Handling non-ASCII and even binary strings.
  csharp/lib/BaseClient.cs
  csharp/lib/Commands/IGenericCommands.cs
  csharp/lib/Commands/IStringBaseCommands.cs
  csharp/lib/GlideClient.cs
  csharp/lib/GlideString.cs
  csharp/lib/Internals/Message.cs
  csharp/lib/Internals/MessageContainer.cs
  csharp/lib/src/lib.rs
  csharp/tests/Integration/SharedCommandTests.cs
  csharp/tests/Integration/StadaloneClientTests.cs
  csharp/tests/Integration/StandaloneClientTests.cs
  csharp/tests/Unit/GildeStringTests.cs
Labels: C#

#3353 C#: routing
  csharp/lib/BaseClient.cs
  csharp/lib/Commands/IGenericClusterCommands.cs
  csharp/lib/GlideClient.cs
  csharp/lib/GlideClusterClient.cs
  csharp/lib/Route.cs
  csharp/lib/src/ffi.rs
  csharp/lib/src/lib.rs
  csharp/tests/Integration/ClusterClientTests.cs
Labels: C#

#3380 Fix documentation for GlideJson.get method
  node/src/server-modules/GlideJson.ts
Labels: node, docs

#3379 C#: Fix TLS
  csharp/lib/Cargo.toml
Labels: C#

#3377 Java: Fix Flaky `fcall_readonly_function`
  java/integTest/src/test/java/glide/cluster/CommandTests.java
Labels: java, testing, Flaky-tests

#3363 Go: Add bulk args test
  go/integTest/glide_test_suite_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3117 Go: Implement FlushAll, FlushDB commands
  CHANGELOG.md
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/options/flush_mode_options.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_cluster_commands_test.go
  go/api/server_management_commands.go
  go/api/server_management_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3346 Go: Add support for updating connection password
  CHANGELOG.md
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/update_connection_password_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
  go/src/lib.rs
Labels: go

#3382 C#: CI - fix dotnet installation on mac runners
  .github/workflows/csharp.yml
Labels: C#, CI/CD

#3413 Fix: Update CI Job names with required config params
  .github/workflows/csharp.yml
  .github/workflows/go.yml
  .github/workflows/java.yml
  .github/workflows/node.yml
  .github/workflows/python.yml
Labels: CI/CD

#3370 Node: Enable +/-inf as score for ZADD
  CHANGELOG.md
  node/npm/glide/index.ts
  node/src/BaseClient.ts
  node/src/Commands.ts
  node/src/Transaction.ts
  node/tests/SharedTests.ts
  node/tests/TestUtilities.ts
Labels: node

#3409 Go: add command GeoPos
  CHANGELOG.md
  go/api/base_client.go
  go/api/geospacial_commands.go
  go/api/geospacial_commands_test.go
  go/api/response_handlers.go
  go/integTest/shared_commands_test.go
Labels: go

#3364 Java: Fix `scriptKill` Flaky Tests
  java/integTest/src/test/java/glide/cluster/CommandTests.java
  java/integTest/src/test/java/glide/standalone/CommandTests.java
Labels: java, testing, Flaky-tests

#3407 GO: Implement Bitpos command
  CHANGELOG.md
  go/api/base_client.go
  go/api/bitmap_commands.go
  go/api/bitmap_commands_test.go
  go/api/options/bitpos_options.go
  go/integTest/shared_commands_test.go
Labels: go

#3077 Go: Implement ClientId
  CHANGELOG.md
  go/api/connection_management_cluster_commands.go
  go/api/connection_management_cluster_commands_test.go
  go/api/connection_management_commands.go
  go/api/connection_management_commands_test.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/response_handlers.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3086 Go: Implement LastSave command
  CHANGELOG.md
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_cluster_commands_test.go
  go/api/server_management_commands.go
  go/api/server_management_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3121 Go: Implement ConfigResetStat
  CHANGELOG.md
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_cluster_commands_test.go
  go/api/server_management_commands.go
  go/api/server_management_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3330 Authentication: Fix immediate update_connection_password to use username
  glide-core/redis-rs/redis/src/client.rs
  glide-core/redis-rs/redis/src/cluster_async/mod.rs
  glide-core/src/client/mod.rs
  glide-core/src/client/reconnecting_connection.rs
  glide-core/src/client/standalone_client.rs
  java/integTest/src/test/java/glide/TestUtilities.java
  java/integTest/src/test/java/glide/cluster/ClusterClientTests.java
  java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java
  node/tests/AuthTest.test.ts
  python/python/tests/conftest.py
  python/python/tests/test_auth.py
  python/python/tests/utils/utils.py
Labels: node, Rust core, Core changes

#3448 Node: Re-enable `xpendingWithOptions` in Transaction Tests
  node/tests/TestUtilities.ts
Labels: node, testing, Flaky-tests

#3385 Go: Add command `GeoSearch`
  CHANGELOG.md
  go/api/base_client.go
  go/api/geospacial_commands.go
  go/api/geospacial_commands_test.go
  go/api/options/constants.go
  go/api/options/geosearch_options.go
  go/api/response_handlers.go
  go/integTest/shared_commands_test.go
Labels: go

#3449 Node: Fix Cluster Manager Timeout
  utils/cluster_manager.py
Labels: node, testing, Flaky-tests

#3274 Go: Implement Cluster ConfigGet and ConfigSet
  CHANGELOG.md
  go/api/glide_cluster_client.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_cluster_commands_test.go
  go/integTest/cluster_commands_test.go
Labels: go

#3302 Go Implement Client Get and Set Name
  CHANGELOG.md
  go/api/connection_management_cluster_commands.go
  go/api/connection_management_cluster_commands_test.go
  go/api/connection_management_commands.go
  go/api/connection_management_commands_test.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3369 Go: Implement move command
  CHANGELOG.md
  go/api/generic_commands.go
  go/api/generic_commands_test.go
  go/api/glide_client.go
  go/integTest/standalone_commands_test.go
Labels: go

#3378 Go: Implement Scan
  CHANGELOG.md
  go/api/generic_commands.go
  go/api/generic_commands_test.go
  go/api/glide_client.go
  go/api/options/scan_options.go
  go/integTest/standalone_commands_test.go
Labels: go

#3447 Node: Fix `scriptKill` Flaky Tests
  node/tests/GlideClient.test.ts
  node/tests/GlideClusterClient.test.ts
Labels: node, testing, Flaky-tests
