Repository valkey-io/valkey-glide, pull requests merged in 2025-05, with the labels that each got.

#3725 Go: Enable AddressSanitizer in integration tests
  go/Makefile
Labels: go

#3708 Go: pubsub shardnumsub command
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/pubsub_commands.go
  go/api/pubsub_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/pubsub_basic_test.go
  go/integTest/pubsub_commands_test.go
Labels: go

#3466 Core: OpenTelemetry metrics infrastructure
  .github/workflows/rust.yml
  CHANGELOG.md
  csharp/rust/src/ffi.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
  glide-core/src/client/mod.rs
  glide-core/src/client/types.rs
  glide-core/src/protobuf/connection_request.proto
  glide-core/telemetry/Cargo.toml
  glide-core/telemetry/src/lib.rs
  glide-core/telemetry/src/metrics_exporter_file.rs
  glide-core/telemetry/src/open_telemetry.rs
  glide-core/telemetry/src/span_exporter_file.rs
  glide-core/tests/test_cluster_client.rs
  node/src/BaseClient.ts
Labels: 2_0_candidate

#3724 Fix function tests
  .gitignore
  node/jest.config.ts
  node/package.json
  node/rust-client/Cargo.toml
  node/rust-client/package.json
  node/rust-client/src/lib.rs
  node/tests/GlideClient.test.ts
  node/tests/GlideClusterClient.test.ts
  node/tests/PubSub.test.ts
  node/tests/ScanTest.test.ts
  node/tests/ServerModules.test.ts
  node/tests/SharedTests.ts
  node/tests/TestUtilities.ts
  node/tests/tsconfig.json
  node/tsconfig.json
  node/types/globals.d.ts
  package.json
  utils/cluster_manager.py
Labels: node, testing, 2_0_candidate

#3555 Python: Add Batch support
  .github/workflows/python.yml
  CHANGELOG.md
  python/dev_requirements.txt
  python/python/glide/__init__.py
  python/python/glide/async_commands/batch.py
  python/python/glide/async_commands/cluster_commands.py
  python/python/glide/async_commands/core.py
  python/python/glide/async_commands/server_modules/json_batch.py
  python/python/glide/async_commands/standalone_commands.py
  python/python/glide/glide_client.py
  python/tests/test_api_export.py
  python/tests/test_async_client.py
  python/tests/test_batch.py
  python/tests/tests_server_modules/test_json.py
Labels: python, breaking

#3752 Go: fix build for 133
  CHANGELOG.md
  go/Makefile
  go/api/base_client.go
  go/api/options/constants.go
  go/api/options/geoadd_options.go
  go/api/options/geosearch_options.go
  go/api/options/zintercard_options.go
  go/api/options/zunion_options.go
  go/api/response_handlers.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3754 Java: Fix flaky `zscan` and `zscan_binary`
  java/integTest/src/test/java/glide/SharedCommandTests.java
Labels: java, Flaky-tests

#3560 C#: panic handling.
  csharp/rust/Cargo.toml
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/Internals/MessageContainer.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ErrorHandlingTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedClientTests.cs
Labels: C#

#3734 C#: Activate and fix disabled tests
  csharp/tests/Valkey.Glide.IntegrationTests/SharedClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C#

#3745 Refactor batch retry strategy: rename to ClusterBatchRetryStrategy
  java/client/src/main/java/glide/api/commands/GenericClusterCommands.java
  java/client/src/main/java/glide/api/models/commands/batch/ClusterBatchOptions.java
  java/client/src/main/java/glide/api/models/commands/batch/ClusterBatchRetryStrategy.java
  java/client/src/test/java/glide/api/GlideClusterClientTest.java
  java/client/src/test/java/glide/managers/CommandManagerTest.java
Labels: java

#3731 Go: Add Function Kill Tests
  go/integTest/cluster_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/test_utils.go
Labels: go

#3760 Cpp client
  .gitignore
  .vscode/settings.json
  cpp/.clang-format
  cpp/CMakeLists.txt
  cpp/Cargo.toml
  cpp/DEVELOPER.md
  cpp/README.md
  cpp/benchmarks/CMakeLists.txt
  cpp/benchmarks/benchmark.cc
  cpp/cbindgen.toml
  cpp/docs/Doxyfile
  cpp/examples/CMakeLists.txt
  cpp/examples/main.cc
  cpp/include/glide/callback.h
  cpp/include/glide/client.h
  cpp/include/glide/config.h
  cpp/include/glide/future.h
  cpp/include/glide/helper.h
  cpp/shell.nix
  cpp/src/callback.cc
  cpp/src/client.cc
  cpp/src/config.cc
  cpp/src/future.cc
  cpp/src/helper.cc
  cpp/src/lib.rs
  cpp/tests/CMakeLists.txt
  cpp/tests/client_test.cc
Labels: C++

#3611 C#: batch
  csharp/rust/Cargo.toml
  csharp/rust/src/ffi.rs
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/Commands/IGenericClusterCommands.cs
  csharp/sources/Valkey.Glide/Commands/IGenericCommands.cs
  csharp/sources/Valkey.Glide/Commands/IStringBaseCommands.cs
  csharp/sources/Valkey.Glide/ConnectionConfiguration.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/GlideString.cs
  csharp/sources/Valkey.Glide/Internals/FFI.cs
  csharp/sources/Valkey.Glide/Pipeline/BaseBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/Batch.cs
  csharp/sources/Valkey.Glide/Pipeline/ClusterBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/IBatch.cs
  csharp/sources/Valkey.Glide/Pipeline/Options.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedBatchTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
Labels: C#

#3796 Update full matrix CI
  .github/workflows/full-matrix-tests.yml
Labels: CI/CD

#3787 Add welcome and community sections to documentation files
  CONTRIBUTING.md
  README.md
  cpp/README.md
  csharp/DEVELOPER.md
  docs/README.md
  go/DEVELOPER.md
  java/DEVELOPER.md
  node/README.md
  python/DEVELOPER.md
  python/README.md
Labels: docs

#3839 Python: added pypy support to pypi cd
  .github/workflows/pypi-cd.yml
  python/python/glide/glide_client.py
Labels: python

#3811 Add libasan to AL2 installed dependencies for CI
  .github/workflows/install-shared-dependencies/action.yml
Labels: go, CI/CD

#3798 Fix Inconsistencies in Documentation
  go/api/base_client.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/integTest/glide_test_suite_test.go
  java/client/src/main/java/glide/api/BaseClient.java
  java/client/src/main/java/glide/api/commands/ListBaseCommands.java
  java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
  java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
  java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
  java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
  java/client/src/main/java/glide/api/commands/StringBaseCommands.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
  java/client/src/main/java/glide/api/models/configuration/RequestRoutingConfiguration.java
  node/src/BaseClient.ts
  node/src/Batch.ts
  node/src/GlideClient.ts
  node/src/GlideClusterClient.ts
  python/python/glide/async_commands/batch.py
  python/python/glide/async_commands/cluster_commands.py
  python/python/glide/async_commands/core.py
  python/python/glide/async_commands/standalone_commands.py
  python/python/glide/routes.py
Labels: python, node, java, go, docs

#3806 Go: Update `EchoWithOptions`
  CHANGELOG.md
  go/api/connection_management_cluster_commands.go
  go/api/connection_management_cluster_commands_test.go
  go/api/glide_cluster_client.go
  go/api/options/echo_options.go
  go/integTest/cluster_commands_test.go
Labels: go

#3772 Java / Python / Go: Add 6.2.0 checks for `xrange` and `xrevrange` exclusive ranges and docs
  go/api/base_client.go
  go/api/options/stream_options.go
  go/integTest/shared_commands_test.go
  java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
  java/integTest/src/test/java/glide/SharedCommandTests.java
  python/python/glide/async_commands/batch.py
  python/python/glide/async_commands/core.py
  python/tests/test_async_client.py
Labels: python, java

#3804 Java: Bump `netty`.
  CHANGELOG.md
  java/client/build.gradle
  java/integTest/build.gradle
Labels: java, dependencies

#3004 Java: Shadow `netty` dependencies. - breaking change
  CHANGELOG.md
  java/client/build.gradle
  java/client/src/main/java/glide/api/BaseClient.java
  java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
  java/client/src/main/java/glide/connectors/resources/EpollResource.java
  java/client/src/main/java/glide/connectors/resources/KQueuePoolResource.java
  java/client/src/main/java/glide/connectors/resources/ThreadPoolResource.java
  java/client/src/main/java/module-info.java
  java/client/src/test/java/glide/api/GlideClientCreateTest.java
  java/integTest/build.gradle
  java/integTest/src/test/java/glide/BatchTestUtilities.java
  java/integTest/src/test/java/glide/CustomThreadPoolResourceTest.java
  java/integTest/src/test/java/glide/TestConfiguration.java
  java/integTest/src/test/java/glide/TestUtilities.java
  java/integTest/src/test/java/glide/cluster/ClusterBatchTests.java
  java/integTest/src/test/java/glide/cluster/CommandTests.java
  java/integTest/src/test/java/glide/standalone/CommandTests.java
  java/integTest/src/test/java/module-info.java
Labels: java, breaking

#3465 Python: add support for Trio runtime
  .github/workflows/python.yml
  CHANGELOG.md
  benchmarks/python/python_benchmark.py
  python/.gitignore
  python/DEVELOPER.md
  python/README.md
  python/dev.py
  python/dev_requirements.txt
  python/docs/conf.py
  python/pyproject.toml
  python/python/glide/async_commands/batch.py
  python/python/glide/glide_client.py
  python/requirements.txt
  python/tests/conftest.py
  python/tests/test_api_export.py
  python/tests/test_async_client.py
  python/tests/test_auth.py
  python/tests/test_batch.py
  python/tests/test_proto_coded.py
  python/tests/test_pubsub.py
  python/tests/test_read_from_strategy.py
  python/tests/test_scan.py
  python/tests/test_utils.py
  python/tests/tests_server_modules/test_ft.py
  python/tests/tests_server_modules/test_json.py
  python/tests/utils/utils.py
Labels: python

#3482 CI: Add intel mac
  .github/json_matrices/build-matrix.json
  CHANGELOG.md
  go/README.md
  java/README.md
  java/client/build.gradle
  node/README.md
  node/npm/glide/package.json
  python/README.md
Labels: CI/CD

#3732 Add supported features on readme
  README.md
Labels: docs

#3849 added pypy support to pypi-cd workflow
  .github/workflows/pypi-cd.yml
  python/python/glide/glide_client.py
Labels: python, 2_0_candidate

#3842 Core: Refactor socket listener to use a runtime that lives for the application lifetime
  CHANGELOG.md
  glide-core/src/client/mod.rs
  glide-core/src/socket_listener.rs
Labels: Core changes

#3753 Java: Add support for Java 21
  .github/json_matrices/supported-languages-versions.json
  java/build.gradle
  java/settings.gradle
Labels: java

#3795 Bump rust version
  benchmarks/rust/Cargo.toml
  benchmarks/rust/src/main.rs
  csharp/rust/Cargo.toml
  ffi/Cargo.toml
  ffi/src/lib.rs
  ffi/tests/ffi_client_tests.rs
  glide-core/Cargo.toml
  glide-core/benches/connections_benchmark.rs
  glide-core/benches/memory_benchmark.rs
  glide-core/benches/rotating_buffer_benchmark.rs
  glide-core/src/client/mod.rs
  glide-core/src/client/reconnecting_connection.rs
  glide-core/src/client/standalone_client.rs
  glide-core/src/client/types.rs
  glide-core/src/client/value_conversion.rs
  glide-core/src/request_type.rs
  glide-core/src/rotating_buffer.rs
  glide-core/src/socket_listener.rs
  glide-core/telemetry/Cargo.toml
  glide-core/tests/test_client.rs
  glide-core/tests/test_cluster_client.rs
  glide-core/tests/test_socket_listener.rs
  glide-core/tests/utilities/cluster.rs
  glide-core/tests/utilities/mocks.rs
  glide-core/tests/utilities/mod.rs
  java/Cargo.toml
  java/src/errors.rs
  java/src/ffi_test.rs
  java/src/lib.rs
  java/src/linked_hashmap.rs
  logger_core/Cargo.toml
  logger_core/src/lib.rs
  logger_core/tests/test_logger.rs
  node/rust-client/Cargo.toml
  node/rust-client/src/lib.rs
  python/Cargo.toml
  python/src/lib.rs
Labels: Rust

#3721 Go: Add commands function dump and restore
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/options/constants.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3864 Go: Make spacing and indentation consistent in docs
  go/api/base_client.go
  go/integTest/pubsub_commands_test.go
Labels: go, docs

#3863 Java: Add a note to `wait`
  java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
Labels: java, docs

#3785 Go: Updated Testing Docs and Makefile
  .github/workflows/go.yml
  go/DEVELOPER.md
  go/Makefile
  go/docs/images/FailingTestReportExample.png
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go, docs, testing

#3883 Java: Add toArgs() to restore batch command
  CHANGELOG.md
  java/client/src/main/java/glide/api/BaseClient.java
  java/client/src/main/java/glide/api/models/BaseBatch.java
  java/client/src/main/java/glide/api/models/commands/RestoreOptions.java
  java/client/src/test/java/glide/api/models/BatchTests.java
Labels: java

#3905 Java: Add error restore command
  CHANGELOG.md
  java/client/src/main/java/glide/api/models/commands/RestoreOptions.java
  java/client/src/test/java/glide/api/GlideClientTest.java
  java/integTest/src/test/java/glide/SharedCommandTests.java
Labels: java

#3844 All clients: Update logger
  CHANGELOG.md
  csharp/sources/Valkey.Glide/Logger.cs
  java/client/src/main/java/glide/api/logging/Logger.java
  node/src/Logger.ts
  python/python/glide/logger.py
Labels: docs

#3926 Added head of the line blocking test for refresh slot
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
Labels: testing

#3903 Go: add client library name and version identifiers
  .github/workflows/go-cd.yml
  CHANGELOG.md
  ffi/.cargo/config.toml
  ffi/DEVELOPER.md
  go/Makefile
  go/integTest/shared_commands_test.go
Labels: go

#3891 Go: Rework how error strings are freed.
  ffi/src/lib.rs
  go/api/callbacks.go
Labels: go

#3917 Use short key for testing ObjectEncoding
  go/integTest/shared_commands_test.go
Labels: go, testing

#3897 Core: Added reference counting to the Script container to support multiple instances
  CHANGELOG.md
  glide-core/src/scripts_container.rs
  java/integTest/src/test/java/glide/cluster/CommandTests.java
  java/integTest/src/test/java/glide/standalone/CommandTests.java
  node/rust-client/src/lib.rs
  node/tests/SharedTests.ts
  python/tests/test_async_client.py
Labels: bug, Core changes, 2_0_candidate

#3918 Go: Refactor Function Commands
  go/base_client.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/internal/interfaces/scripting_and_function_base_commands.go
  go/internal/interfaces/scripting_and_function_cluster_commands.go
  go/internal/interfaces/scripting_and_function_standalone_commands.go
Labels: go

#3934 Go: Fix Failing SortWithOptions Tests
  go/integTest/shared_commands_test.go
Labels: go, testing

#3928 Cleanup some files in node, modernize tests, and update the node matrix
  .github/json_matrices/supported-languages-versions.json
  .gitignore
  .gitmodules
  eslint.config.mjs
  node/.gitignore
  node/jest.config.ts
  node/npm/glide/jest.config.js
  node/tests/setup.ts
  utils/package.json
  utils/release-candidate-testing/node/package.json
Labels: node, CI/CD, testing

#3961 Go: Fix Makefile Path for Unit Test
  go/Makefile
Labels: go

#3568 Update engine-matrix.json
  .github/json_matrices/engine-matrix.json
  java/integTest/src/test/java/glide/BatchTestUtilities.java
Labels: CI/CD, valkey

#3893 Reorganize and split tests dir and conftest files
  python/tests/async_tests/conftest.py
  python/tests/async_tests/test_async_client.py
  python/tests/async_tests/test_auth.py
  python/tests/async_tests/test_batch.py
  python/tests/async_tests/test_pubsub.py
  python/tests/async_tests/test_read_from_strategy.py
  python/tests/async_tests/test_scan.py
  python/tests/async_tests/tests_server_modules/test_ft.py
  python/tests/async_tests/tests_server_modules/test_json.py
  python/tests/conftest.py
  python/tests/sync_tests/conftest.py
  python/tests/sync_tests/test_sync_client.py
  python/tests/test_utils.py
  python/tests/utils/utils.py
Labels: python

#3386 Java: implement support for using insecure TLS
  CHANGELOG.md
  java/client/src/main/java/glide/api/models/configuration/AdvancedBaseClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/AdvancedGlideClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/AdvancedGlideClusterClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/GlideClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/GlideClusterClientConfiguration.java
  java/client/src/main/java/glide/api/models/configuration/TlsAdvancedConfiguration.java
  java/client/src/main/java/glide/managers/ConnectionManager.java
  java/client/src/test/java/glide/managers/ConnectionManagerTest.java
  java/integTest/src/test/java/glide/ConnectionTests.java
Labels: java, Feature

#3938 Go: Batch
  ffi/src/lib.rs
  go/base_client.go
  go/batch_test.go
  go/glide_client.go
  go/glide_cluster_client.go
  go/integTest/batch_test.go
  go/integTest/cluster_commands_test.go
  go/internal/interfaces/client_interfaces.go
  go/pipeline/batch.go
  go/response_handlers.go
Labels: go

#3976 Rust clean up - Refactor Redis connection handling and remove ACL and script features
  .vscode/settings.json
  glide-core/Cargo.toml
  glide-core/benches/rotating_buffer_benchmark.rs
  glide-core/redis-rs/redis/Cargo.toml
  glide-core/redis-rs/redis/benches/bench_cluster.rs
  glide-core/redis-rs/redis/benches/bench_cluster_async.rs
  glide-core/redis-rs/redis/examples/geospatial.rs
  glide-core/redis-rs/redis/src/acl.rs
  glide-core/redis-rs/redis/src/cluster.rs
  glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
  glide-core/redis-rs/redis/src/cluster_async/pipeline_routing.rs
  glide-core/redis-rs/redis/src/cluster_client.rs
  glide-core/redis-rs/redis/src/cluster_routing.rs
  glide-core/redis-rs/redis/src/commands/mod.rs
  glide-core/redis-rs/redis/src/connection.rs
  glide-core/redis-rs/redis/src/geo.rs
  glide-core/redis-rs/redis/src/lib.rs
  glide-core/redis-rs/redis/src/retry_strategies.rs
  glide-core/redis-rs/redis/src/script.rs
  glide-core/redis-rs/redis/src/sentinel.rs
  glide-core/redis-rs/redis/tests/support/cluster.rs
  glide-core/redis-rs/redis/tests/support/mod.rs
  glide-core/redis-rs/redis/tests/support/util.rs
  glide-core/redis-rs/redis/tests/test_acl.rs
  glide-core/redis-rs/redis/tests/test_async.rs
  glide-core/redis-rs/redis/tests/test_basic.rs
  glide-core/redis-rs/redis/tests/test_cluster.rs
  glide-core/redis-rs/redis/tests/test_cluster_async.rs
  glide-core/redis-rs/redis/tests/test_cluster_pipeline.rs
  glide-core/redis-rs/redis/tests/test_cluster_scan.rs
  glide-core/redis-rs/redis/tests/test_geospatial.rs
  glide-core/tests/utilities/mod.rs
Labels: Optimization, Users Pain, Rust

#4004 Go: Bitmap Batch Commands Tests
  go/base_client.go
  go/integTest/batch_test.go
  go/pipeline/base_batch.go
Labels: go

#3933 Go: Fix Timeout Casting in `time.Duration`
  go/config/config.go
  go/config/config_test.go
  go/integTest/connection_test.go
  go/integTest/glide_test_suite_test.go
  go/internal/utils/transform_utils.go
Labels: go

#4019 Go: Refactor integration tests to use require assertions
  go/integTest/cluster_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/pubsub_basic_test.go
  go/integTest/pubsub_commands_test.go
  go/integTest/readfrom_strategy_test.go
  go/integTest/shared_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go, Flaky-tests

#4023 Go: Hyperloglog Batch Tests
  go/integTest/batch_test.go
Labels: go

#4009 Go: Add Generic Base Batch Tests
  go/integTest/batch_test.go
Labels: go

#4022 Go: Add Hash Commands to Batch Test
  go/integTest/batch_test.go
Labels: go

#3962 Java: Otel implementation
  CHANGELOG.md
  java/client/src/main/java/glide/api/OpenTelemetry.java
  java/client/src/main/java/glide/ffi/resolvers/OpenTelemetryResolver.java
  java/client/src/main/java/glide/managers/BaseResponseResolver.java
  java/client/src/main/java/glide/managers/CommandManager.java
  java/integTest/src/test/java/glide/OpenTelemetryConfigTests.java
  java/integTest/src/test/java/glide/OpenTelemetryTests.java
  java/src/errors.rs
  java/src/ffi_test.rs
  java/src/lib.rs
Labels: java, Telemetry

#4020 Go: Add Batch Generic Cluster Commands Tests
  go/integTest/batch_test.go
Labels: go
