Repository valkey-io/valkey-glide, pull requests merged in 2025-04, with the labels that each got.

#3082 Go: Implement PfMerge command
  CHANGELOG.md
  go/api/base_client.go
  go/api/hyperloglog_commands.go
  go/api/hyperloglog_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3156 Go: Implement Config Rewrite
  CHANGELOG.md
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_cluster_commands_test.go
  go/api/server_management_commands.go
  go/api/server_management_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3358 Go: Implement Random Key
  CHANGELOG.md
  go/api/generic_cluster_commands.go
  go/api/generic_cluster_commands_test.go
  go/api/generic_commands.go
  go/api/generic_commands_test.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3472 Fix scala example.
  examples/scala/build.sbt
  examples/scala/src/main/scala/ClusterExample.scala
Labels: java, docs

#3475 GO: Implement Lcs command with options
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/options/lcs_options.go
  go/api/string_commands.go
  go/api/string_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3507 Go: Fix Rust static binary size
  go/Makefile
Labels: go

#3489 Fix node type issues
  CHANGELOG.md
  node/npm/glide/tests/ExportedSymbols.test.ts
  node/package.json
  node/src/server-modules/GlideFtOptions.ts
  node/src/server-modules/GlideJson.ts
Labels: node

#3362 C#: Reorganize Structure
  .github/workflows/csharp.yml
  benchmarks/csharp/Program.cs
  benchmarks/csharp/csharp_benchmark.csproj
  csharp/Valkey.Glide.sln
  csharp/csharp.sln
  csharp/rust/.cargo/config.toml
  csharp/rust/Cargo.toml
  csharp/rust/src/ffi.rs
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/Commands/IConnectionManagementCommands.cs
  csharp/sources/Valkey.Glide/Commands/IGenericClusterCommands.cs
  csharp/sources/Valkey.Glide/Commands/IGenericCommands.cs
  csharp/sources/Valkey.Glide/Commands/IStringBaseCommands.cs
  csharp/sources/Valkey.Glide/ConnectionConfiguration.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/GlideString.cs
  csharp/sources/Valkey.Glide/Internals/Message.cs
  csharp/sources/Valkey.Glide/Internals/MessageContainer.cs
  csharp/sources/Valkey.Glide/Logger.cs
  csharp/sources/Valkey.Glide/Properties/AssemblyInfo.cs
  csharp/sources/Valkey.Glide/Route.cs
  csharp/sources/Valkey.Glide/Valkey.Glide.csproj
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/SharedCommandTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
  csharp/tests/Valkey.Glide.IntegrationTests/Valkey.Glide.IntegrationTests.csproj
  csharp/tests/Valkey.Glide.IntegrationTests/xunit.runner.json
  csharp/tests/Valkey.Glide.UnitTests/GildeStringTests.cs
  csharp/tests/Valkey.Glide.UnitTests/Valkey.Glide.UnitTests.csproj
  csharp/tests/Valkey.Glide.UnitTests/xunit.runner.json
Labels: C#

#3474 Go: Add Function Load, Function Flush, FCall, FCallReadOnly
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/response_handlers.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/test_utils.go
Labels: go

#3519 Java: Fix `inflight_request_limit` Flaky Test
  java/integTest/src/test/java/glide/SharedClientTests.java
  java/integTest/src/test/java/glide/SharedCommandTests.java
Labels: java, Flaky-tests

#3394 CI: Address semgrep findings
  .github/workflows/build-node-wrapper/action.yml
  .github/workflows/build-python-wrapper/action.yml
  .github/workflows/create-test-matrices/action.yml
  .github/workflows/install-engine/action.yml
  .github/workflows/lint-ts/action.yml
  .github/workflows/node-create-package-file/action.yml
  .github/workflows/node.yml
  .github/workflows/npm-cd.yml
  .github/workflows/run-ort-tools/action.yml
  .github/workflows/setup-musl-on-linux/action.yml
  .github/workflows/start-self-hosted-runner/action.yml
  .github/workflows/test-benchmark/action.yml
  .github/workflows/update-glide-version/action.yml
Labels: CI/CD

#3381 CI: Fix benchmarking on SH runner.
  .github/workflows/csharp.yml
  .github/workflows/test-benchmark/action.yml
Labels: CI/CD

#3523 Java: Disable Flaky Tests
  java/integTest/src/test/java/glide/cluster/CommandTests.java
Labels: java, Flaky-tests

#3395 C#: Handle all response types.
  csharp/rust/src/ffi.rs
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/Internals/Message.cs
  csharp/sources/Valkey.Glide/Internals/ResponseHandler.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
Labels: C#

#3520 Downgrade ubuntu in CI
  .github/json_matrices/build-matrix.json
  .github/workflows/rust.yml
  go/README.md
  java/README.md
  node/README.md
  python/README.md
Labels: CI/CD

#3548 Go: fix documentation address typo
  go/api/config.go
Labels: bug, go, docs

#3513 Go: Drop support for Go 1.20 and add 1.24 in CI
  .github/json_matrices/supported-languages-versions.json
  .github/workflows/go-cd.yml
  .github/workflows/go.yml
  CHANGELOG.md
  go/DEVELOPER.md
  go/Makefile
  go/README.md
  go/api/pinner_old.go
  go/benchmarks/go.mod
  go/benchmarks/go.sum
  go/go.mod
Labels: go, breaking

#3558 Python: Add equality check to ExpirySet
  CHANGELOG.md
  python/python/glide/async_commands/core.py
  python/python/tests/test_async_client.py
Labels: python

#3552 Update README.md
  node/README.md
Labels: node, docs

#3572 Added docs folder and infrastructure for mkdocs website
  .gitignore
  docs/build-docs.sh
  docs/markdown/index.md
  docs/markdown/python/base_client.md
  docs/markdown/python/base_transaction.md
  docs/markdown/python/cluster_commands.md
  docs/markdown/python/cluster_transaction.md
  docs/markdown/python/config.md
  docs/markdown/python/core.md
  docs/markdown/python/exceptions.md
  docs/markdown/python/glide_client.md
  docs/markdown/python/glide_cluster_client.md
  docs/markdown/python/index.md
  docs/markdown/python/standalone_command.md
  docs/markdown/python/standalone_transaction.md
  docs/mkdocs.yml
  node/build-docs
  node/package.json
  node/typedoc.json
Labels: python, node, docs

#3566 Java: Fix compiler warning
  java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java
Labels: java

#3573 Java: Fix `send_and_receive_large_values` and `test_update_connection_password_acl_user`
  java/integTest/src/test/java/glide/SharedClientTests.java
  java/integTest/src/test/java/glide/cluster/ClusterClientTests.java
Labels: java, Flaky-tests

#3574 Node: Fix `ExportedSymbols.test.ts` Missing Dependency
  node/npm/glide/index.ts
Labels: node

#3556 Go: fix geo tests.
  go/integTest/shared_commands_test.go
Labels: go, testing

#3584 Java: Fix scan tests and `client_can_handle_concurrent_workload` timing out
  java/integTest/src/test/java/glide/SharedClientTests.java
  java/integTest/src/test/java/glide/SharedCommandTests.java
Labels: java, Flaky-tests

#3583 C#: Give client an ID
  csharp/sources/Valkey.Glide/BaseClient.cs
Labels: C#

#3526 Add command FUNCTION STATS
  CHANGELOG.md
  go/api/function_command_results.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/response_handlers.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/api/scripting_and_function_standalone_commands.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3483 CD: Add `publish` checkbox for node and python CD.
  .github/workflows/go-cd.yml
  .github/workflows/npm-cd.yml
  .github/workflows/pypi-cd.yml
Labels: CI/CD

#3417 PubSub base framewwork - Part 1
  CHANGELOG.md
  ffi/src/lib.rs
  ffi/tests/ffi_client_tests.rs
  go/api/base_client.go
  go/api/callbacks.go
  go/api/config.go
  go/api/errors/errors.go
  go/api/glide_client.go
  go/api/pubsub_commands.go
  go/api/pubsub_message.go
  go/api/pubsub_message_handler.go
  go/api/pubsub_subscription_config.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/PubSubGoTestPlan.md
  go/integTest/pubsub_basic_test.go
  go/integTest/pubsub_config_test.go
  go/integTest/pubsub_handler_test.go
  go/integTest/pubsub_test_suite_helpers.go
  go/integTest/pubsub_test_suite_test.go
  go/utils/transform_utils.go
Labels: Feature, go

#3418 Docs: Fix docs and examples for client class and constructor.
  CHANGELOG.md
  go/api/create_client_test.go
  go/api/example_utils.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  java/client/src/main/java/glide/api/GlideClient.java
  java/client/src/main/java/glide/api/GlideClusterClient.java
  node/src/GlideClient.ts
  node/src/GlideClusterClient.ts
  python/python/glide/glide_client.py
Labels: docs

#3596 Ensure the UDS socket filename is truly unique
  CHANGELOG.md
  glide-core/Cargo.toml
  glide-core/src/socket_listener.rs
Labels: Core changes

#3587 Java: Fix Flaky `config_reset_stat`
  java/integTest/src/test/java/glide/cluster/CommandTests.java
Labels: java, Flaky-tests

#3602 Python: Updated `DEVELOPER.md` with notes on `mkdocs`
  python/DEVELOPER.md
Labels: python, docs

#3598 Java: update doc for FUNC STAT under cluster mode
  java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
Labels: docs

#3594 Go: Fix `CONFIG GET`.
  CHANGELOG.md
  go/api/glide_cluster_client.go
  go/api/response_handlers.go
  go/api/server_management_cluster_commands.go
  go/api/server_management_cluster_commands_test.go
Labels: go

#3610 Node: Update FUNCTION STATS doc under cluster mode
  node/src/GlideClusterClient.ts
Labels: node, docs

#3581 Docs website: Added CD, added node script, some hirarchy changes
  .github/workflows/mkdocs-deploy.yml
  .gitignore
  docs/README.md
  docs/markdown/python/config.md
  docs/markdown/python/logger.md
  docs/markdown/python/standalone_commands.md
  docs/mkdocs.yml
  node/docs/build-docs
  node/docs/convert-urls.mjs
  node/docs/typedoc.json
  node/package.json
Labels: python, node, docs

#3603 Go: Add command FUNCTION DELETE
  CHANGELOG.md
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/api/scripting_and_function_standalone_commands.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3534 CI: Fix caching
  .github/json_matrices/build-matrix.json
  .github/workflows/create-test-matrices/action.yml
  .github/workflows/csharp.yml
  .github/workflows/go.yml
  .github/workflows/install-engine/action.yml
  .github/workflows/java.yml
  .github/workflows/lint-rust/action.yml
  .github/workflows/node.yml
  .github/workflows/python.yml
  .github/workflows/rust.yml
Labels: CI/CD

#3612 C#: benchmark fix
  benchmarks/csharp/Program.cs
Labels: C#

#3616 Updates READMEs with docs site
  README.md
  node/README.md
  python/README.md
Labels: docs

#3391 Node: add span command to measure command latency
  CHANGELOG.md
  csharp/rust/src/ffi.rs
  glide-core/redis-rs/redis/src/cmd.rs
  glide-core/redis-rs/redis/src/pipeline.rs
  glide-core/src/client/mod.rs
  glide-core/src/client/types.rs
  glide-core/src/lib.rs
  glide-core/src/protobuf/command_request.proto
  glide-core/src/protobuf/connection_request.proto
  glide-core/src/protobuf/response.proto
  glide-core/src/socket_listener.rs
  glide-core/telemetry/src/open_telemetry.rs
  glide-core/telemetry/src/open_telemetry_exporter_file.rs
  glide-core/tests/test_cluster_client.rs
  node/rust-client/src/lib.rs
  node/src/BaseClient.ts
  node/tests/OpenTelemetry.test.ts
  node/tests/ScanTest.test.ts
Labels: node, 2_0_candidate

#3623 Java: Re-enable `test_update_connection_password`
  java/integTest/src/test/java/glide/cluster/ClusterClientTests.java
Labels: java, Flaky-tests

#3412 C#: Compile on C# 10 (.net 6)
  .github/workflows/csharp.yml
  benchmarks/csharp/csharp_benchmark.csproj
  csharp/sources/Valkey.Glide/Valkey.Glide.csproj
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
  csharp/tests/Valkey.Glide.IntegrationTests/Valkey.Glide.IntegrationTests.csproj
  csharp/tests/Valkey.Glide.UnitTests/Valkey.Glide.UnitTests.csproj
Labels: C#

#3604 Go: Add command FUNCTION KILL
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/test_utils.go
Labels: go

#3593 Fix custom command response handling
  CHANGELOG.md
  go/api/glide_cluster_client.go
  go/integTest/cluster_commands_test.go
  go/integTest/readfrom_strategy_test.go
  java/client/src/main/java/glide/api/GlideClusterClient.java
  java/integTest/src/test/java/glide/cluster/CommandTests.java
Labels: java, go

#3411 C#: Error handling.
  .vscode/settings.json
  benchmarks/csharp/Program.cs
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/Errors.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ErrorHandlingTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C#

#3638 Create stale.yml
  .github/workflows/stale.yml
Labels: CI/CD

#3630 Core/Go: Added Ok response type to FFI, updated Go with Ok handlers
  CHANGELOG.md
  ffi/src/lib.rs
  go/api/base_client.go
  go/api/generic_base_commands.go
  go/api/generic_base_commands_test.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/response_handlers.go
  go/api/update_connection_password_test.go
  go/integTest/shared_commands_test.go
Labels: go, Core changes

#3648 Node: Fix comment for `keepExisting` in `SetOptions`
  node/src/Commands.ts
Labels: node, docs

#3621 PubSub Framework: Cluster Client Support Part 2
  ffi/src/lib.rs
  go/api/base_client.go
  go/api/config.go
  go/api/glide_cluster_client.go
  go/api/pubsub_commands.go
  go/api/pubsub_message_handler.go
  go/api/pubsub_subscription_config.go
  go/integTest/PubSubGoTestPlan.md
  go/integTest/glide_test_suite_test.go
  go/integTest/pubsub_basic_test.go
  go/integTest/pubsub_config_test.go
  go/integTest/pubsub_handler_test.go
  go/integTest/pubsub_test_suite_helpers.go
  go/integTest/pubsub_test_suite_test.go
Labels: go

#3541 Python: Added dev.py script to manage the python development workflows
  .github/workflows/build-python-wrapper/action.yml
  .github/workflows/pypi-cd.yml
  .github/workflows/python.yml
  Makefile
  ffi/Cargo.toml
  python/.flake8
  python/Cargo.toml
  python/DEVELOPER.md
  python/dev.py
  python/dev_requirements.txt
  python/pyproject.toml
  python/tests/test_transaction.py
Labels: python, CI/CD

#3649 Go/edlng script exists
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3670 Go: Add `SCRIPT KILL`
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_cluster_client.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
  go/integTest/test_utils.go
Labels: go

#3665 GO: pubsub channels command
  CHANGELOG.md
  go/api/base_client.go
  go/api/example_utils.go
  go/api/pubsub_commands.go
  go/api/pubsub_commands_test.go
  go/integTest/pubsub_commands_test.go
Labels: go

#3626 C#: refactor for FFI
  csharp/rust/src/ffi.rs
  csharp/rust/src/lib.rs
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/ConnectionConfiguration.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/GlideString.cs
  csharp/sources/Valkey.Glide/Internals/FFI.cs
  csharp/sources/Valkey.Glide/Internals/ResponseHandler.cs
  csharp/sources/Valkey.Glide/Route.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C#

#3589 C#: `ClusterValue` + `INFO`
  csharp/sources/Valkey.Glide/BaseClient.cs
  csharp/sources/Valkey.Glide/ClusterValue.cs
  csharp/sources/Valkey.Glide/Commands/IGenericClusterCommands.cs
  csharp/sources/Valkey.Glide/Commands/IServerManagementClusterCommands.cs
  csharp/sources/Valkey.Glide/Commands/IServerManagementCommands.cs
  csharp/sources/Valkey.Glide/Commands/Options/InfoOptions.cs
  csharp/sources/Valkey.Glide/GlideClient.cs
  csharp/sources/Valkey.Glide/GlideClusterClient.cs
  csharp/sources/Valkey.Glide/GlideString.cs
  csharp/sources/Valkey.Glide/Internals/FFI.cs
  csharp/sources/Valkey.Glide/Internals/Helpers.cs
  csharp/sources/Valkey.Glide/Internals/ResponseHandler.cs
  csharp/tests/Valkey.Glide.IntegrationTests/ClusterClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/StandaloneClientTests.cs
  csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Labels: C#

#3668 Go: Script show command added
  CHANGELOG.md
  go/api/base_client.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3667 Fixes to mkdocs site
  .github/workflows/mkdocs-deploy.yml
  docs/build-docs.sh
  docs/markdown/python/glide_client.md
  docs/markdown/python/glide_cluster_client.md
  docs/markdown/style.css
  docs/mkdocs.yml
Labels: docs

#3606 Update supported languages and versions in configuration files, added…
  .github/json_matrices/supported-languages-versions.json
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  node/README.md
  node/package.json
  node/rust-client/Cargo.toml
  node/rust-client/package.json
  package.json
Labels: node, Optimization, CI/CD, Platforms, 2_0_candidate, dependencies

#3674 Go: pubsub numsub command
  CHANGELOG.md
  go/api/base_client.go
  go/api/pubsub_commands.go
  go/api/pubsub_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/pubsub_commands_test.go
Labels: go

#3692 Go: PubSub Publish Sharded
  CHANGELOG.md
  go/api/base_client.go
  go/api/glide_client.go
  go/api/glide_cluster_client.go
  go/api/pubsub_commands.go
  go/api/pubsub_commands_test.go
  go/integTest/glide_test_suite_test.go
  go/integTest/pubsub_basic_test.go
  go/integTest/readfrom_strategy_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3676 Java: Prevent Scan Tests from Timing Out
  java/integTest/src/test/java/glide/SharedCommandTests.java
Labels: java, Flaky-tests

#3669 Java: activate pubsub tests on mac
  java/integTest/src/test/java/glide/PubSubTests.java
Labels: java, testing

#3673 Go: Add Function List
  CHANGELOG.md
  go/api/base_client.go
  go/api/function_command_results.go
  go/api/glide_cluster_client.go
  go/api/options/constants.go
  go/api/response_handlers.go
  go/api/scripting_and_function_base_commands.go
  go/api/scripting_and_function_cluster_commands.go
  go/api/scripting_and_function_commands_test.go
  go/integTest/cluster_commands_test.go
  go/integTest/standalone_commands_test.go
Labels: go

#3695 Go: pubsub shardchannels
  CHANGELOG.md
  go/api/glide_cluster_client.go
  go/api/pubsub_commands.go
  go/api/pubsub_commands_test.go
  go/integTest/pubsub_commands_test.go
Labels: go

#3706 Python: fix PARAMS count in ft.search query
  python/python/glide/async_commands/server_modules/ft_options/ft_search_options.py
  python/tests/tests_server_modules/test_ft.py
Labels: python

#3694 Go: Fix `ZRangeWithScores` Order
  CHANGELOG.md
  go/api/base_client.go
  go/api/response_handlers.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go

#3719 Don't run some CI on repo forks
  .github/workflows/mkdocs-deploy.yml
  .github/workflows/ort-sweeper.yml
  .github/workflows/ort.yml
  .github/workflows/semgrep.yml
  .github/workflows/stale.yml
Labels: CI/CD

#3712 Go: Fix Ordering of Sorted Set With Scores Commands
  CHANGELOG.md
  go/api/base_client.go
  go/api/response_handlers.go
  go/api/sorted_set_commands.go
  go/api/sorted_set_commands_test.go
  go/integTest/shared_commands_test.go
Labels: go
